### ISSUE TITLE
Peacock 1.2.1 not compatible with Code 1.28.2

### ISSUE THREAD

**Issue by bothzoli** [johnpapa/vscode-peacock#100]
# Unable to install Peacock on Code 1.28.2

## Version Information

OS: Windows 10 Enterprise
VS Code Version: Stable 1.28.2
Extension version: johnpapa.vscode-peacock-1.2.1

## Repro steps

I tried to install Peacock from directly in VS Code.
Here I got the error message _Failed to install `johnpapa.vscode-peacock'._
And a button _Download Manually_.

This downloaded the VSIX file `johnpapa.vscode-peacock-1.2.1.vsix`, and when trying to install that manually I got the _Unable to install Extension 'johnpapa.vscode-peacock-1.2.1' as it is not compatible with Code '1.28.2'._

## The log given by the failure

I'm not sure if it's this, but I found this in the _Log (Shared)_ part of `OUTPUT`:

`[error] Failed to install extension: johnpapa.vscode-peacock Unable to install because, the depending extension 'johnpapa.vscode-peacock' compatible with current version '1.28.2' of VS Code is not found.`

**Comment by johnpapa** [comment]
You can try updating your version of VS Code.

When I generated the extension from their tooling, it added this requirement. I'm hesitant to lower it as I do not know what versions support which APIs, in the past.
```
  "engines": {
    "vscode": "^1.31.0"
  },
```

**Comment by bothzoli** [comment]
so this made me realize that somehow the auto-update was switched off in my VS Code... 😊
thanks, after update it works like a charm

**Comment by johnpapa** [comment]
no worries. it happens :)
