### ISSUE TITLE
Bug: Surprise Me On Startup information message appears with command

### ISSUE THREAD

**Issue by musicfuel** [johnpapa/vscode-peacock#104]
As part of the changes in #81 to support the "Surprise Me On Startup" setting an info message was added to display when Peacock applies the change. The message is currently appearing any time the "Surprise Me with a random color" command is run which is sometimes incorrect because it mentions "because the setting is enabled for supriseMeOnStartup" even if the setting is not enabled.

## Version Information

> macOS 10.14
> VS Code 1.32.3 (stable)
> Peacock 1.3.0

## Repro steps

1. Edit settings and ensure that "Surprise Me on Startup" is not enabled
1. Run the "Surprise Me with a Random Color" command
1. Observe that the info message appears stating "Peacock changed the base accent colors to #XXXXXX, because the searing is enabled for surpriseMeOnStartup"

## Mention any other details that might be useful

I found this just playing with Peacock 1.3 a bit today. I think the info message in response to the setting is great, but the message it gives can be deceiving if the setting is not actually set. Two thoughts on resolutions:

* Fix the issue so that this message _only_ appears after startup in response to the setting and not when the command is run.
* Keep the message, but tailor the content so that the setting message only appears in response to the setting after startup. This would mean that after the "Surprise Me with a Random Color" is run the message would be only "Peacock changed the base accent colors to #XXXXXX"

**Comment by johnpapa** [comment]
Thanks for reporting this. I'll take a look at a patch ASAP

**Comment by johnpapa** [comment]
pushed a fix and published as 1.3.1


I chose 

> Fix the issue so that this message only appears after startup in response to the setting and not when the command is run.
