### ISSUE TITLE
Feature Request: To generate unique color for each project

### ISSUE THREAD

**Issue by motss** [johnpapa/vscode-peacock#105]
_This is not a issue ticket!_

It would be a great-to-have feature when using the `Surprise me with a random color` feature could help generate a unique color for each different project so that no different projects using the same color for better distinction.

**Comment by hajnyon** [comment]
Just FYI there is already an extension for that: [Window Colors](https://marketplace.visualstudio.com/items?itemName=stuart.unique-window-colors). It changes window color based on current project hash, so each project has different color. However thanks to this random feature you get random colors, which you don't have to like (my case, thats why I found peacock to be much better choice).

**Comment by johnpapa** [comment]
Neat idea - but closing this for now. If a proposal comes through, we can reopen.
