### ISSUE TITLE
Error when peac a color with no opened workspace

### ISSUE THREAD

**Issue by ahdbk** [johnpapa/vscode-peacock#106]
# Error when peac a color with no opened workspace

> ## Please provide us with the following information:

## Version Information

> Windows 7
> VS Code version 1.31.1
> Version of Peacock 131

## Repro steps

>open VC Code (without opning workspace or folder)
> Try to change color

## The log given by the failure

>
![image](https://user-images.githubusercontent.com/2827484/54535957-fae56780-498f-11e9-95a9-c38505365fc2.png)

> Thanks! We'll be in touch soon.

**Comment by johnpapa** [comment]
Yes, that is correct. VS Code does not support workspace settings unless at least one folder is open, AFAIK. If this is not what happened , please let me know.

Closing as this is part of VS Code
