### ISSUE TITLE
Built-In Colors: Expand them? Replace with Favorites? Keep them as-is? Something Else?

### ISSUE THREAD

**Issue by EisenbergEffect** [johnpapa/vscode-peacock#112]
John, I LOVE this! Thank you for building it 😄 

Would you take a PR to add an Aurelia color default setting based on our brand colors? We'll put it together and send it your way if you'd be willing to accept that.

Let me know and thank you again. This is super cool 😎

**Comment by johnpapa** [comment]
Hi Rob, thanks - and I'm happy you like it.

I'm being transparent on this so everyone can see my thinking :)

I'm currently evaluating what to do with the built in colors. I like having a small set built-in, but now with favorites it may make more sense to remove these built-in colors. Possibly to add them back in as default favorites.

Or I could keep the built-ins and keep them at 3 ... or expand them (but if I do, it would be a small set still).

Ultimately, I am not ready to make this call. I'll keep this open and rename the issue as I consider what to do with the built-ins.

**Comment by musicfuel** [comment]
I like your thinking on this @johnpapa. On the one hand, having the defaults is super handing and keeps with the branding of the individual frameworks nicely. On the other, it does feel that maybe these shouldn't be first-party Peacock commands in their own right. I say this because:

* It elevates them to a higher prominence in the plugin than other colors
* It add more, it requires adding more commands which will make the command list daunting eventually 

I think your idea of making a default set of Favorites is the right approach. That list can easily scale up without blowing up the total number of commands and shifting them in there will reduce the list of commands making the plugin easier to use.

**Comment by EisenbergEffect** [comment]
It seems to me that there should be a single command to apply a preset. Then, once you execute that command, you get the alphabetized list of presets. Let anyone who wants submit a PR for a preset.

**Comment by johnpapa** [comment]
There is a command for favorites (what you call presets). And this is where I am leaning - and this removing the built in colors. 

The number of baked in favorites Is something I’m debating too. 

I think I have some ideas on how to do this but I’m open to any feedback.

**Comment by johnpapa** [comment]
Working through some of this and putting my thoughts here.

**Desired process**

The way I'd like it to work is when the user installs the extension, they are prompted to add the recommended favorites. (or maybe by default this happens). I'm shooting for an out of the box experience of having some favorites. The key here is that today, there is no clear way to indicate if the extension has "just" been installed. 

**Issues**

1. I could add a command that let's the user opt into the recommended favorites at any time (adding these to what they have). Pro - this is easy. Con - this requires the user to discover it and this is not an out of the box experience.

2. I could make a new config setting to toggle this. Pro - it works. Con - it is easily overridden, is a setting that really is a workaround the API, user could easily change it and not know what it does. This feels wrong.

3. I could add favorites as the defaults. Pros - user gets the favorites out of the box. ons - they disappear as soon as new favorites are added by the user. This is not ideal.

4. On activation if there are no favorites currently, I could make Peacock prompt the user (opt in) to add the recommended favorites. Pro - this works. Con - this runs the risk of being annoying.

It would be great if there was an API for `install`. Or ... It would be great to be able to check if any settings for peacock exist. Today we can only check the value of a setting. Not the existence of it (e.g. default of true in package.json would return true even if the setting is not in the settings.json)

**Comment by johnpapa** [comment]
closed by #117
