### ISSUE TITLE
Peacock amends .vscode project settings

### ISSUE THREAD

**Issue by akaRem** [johnpapa/vscode-peacock#124]
Once any project is opened, `.vscode/settings.json` is patched with something like this:
```
  "workbench.colorCustomizations": {
    "[Theme-name]": { ... }
    "activityBar.background": "#fbed80",
    "activityBar.foreground": "#15202b",
    "activityBar.inactiveForeground": "#15202b99",
    "activityBarBadge.background": "#06b9a5",
    "activityBarBadge.foreground": "#15202b",
    "titleBar.activeBackground": "#f9e64f",
    "titleBar.inactiveBackground": "#f9e64f99",
    "titleBar.activeForeground": "#15202b",
    "titleBar.inactiveForeground": "#15202b99"
  }
```
The problem is that we put these files to repo because they contain file associations, recommended plugins, etc.
But only important stuff.

Color overrides should not be commited, 
User's colour overrides for schemes should not be commited.

**Comment by johnpapa** [comment]
this is a duplicate of #7 

There currently is now API for saving settings for one user on one project.
