### ISSUE TITLE
Idea: Generate color from folder path

### ISSUE THREAD

**Issue by Riduidel** [johnpapa/vscode-peacock#129]
## Version Information

> Windows 10
> VS Code version? 1.32.3
> Not installed as of today

I've tried peacock, which is full of good ideas.
However, one thing that turns me back is the fact that color is chosen randomly.
[unique-window-colors](https://github.com/stuartcrobinson/unique-window-colors/), on the other side, generates the clor of the windows from the path (as far as I can tell), which ensures consistent color scheme (the same project always has the same color).
Could this feature be implemented in Peacock ?

**Comment by johnpapa** [comment]
Thanks for the comment. It certainly is an option, but not on my roadmap right now.

Right now your options are:
- Choose a random color
- Enter a color
- Create your own favorite and choose it when desired

**Comment by blackjid** [comment]
I would totally love this!

**Comment by johnpapa** [comment]
Neat idea - but closing this for now. If a proposal comes through, we can reopen.

**Comment by 5pecia1** [comment]
I suggest using [this](https://stackoverflow.com/a/16348977/6712960) to create a color.
