### ISSUE TITLE
Idea: Random Color from selection

### ISSUE THREAD

**Issue by jaydeflix** [johnpapa/vscode-peacock#131]
Random color selection from selection

Scenario:

I do like the ability to select a random color, but I'd like to be able to limit the choices.

Multiple possible solutions:
A second 'favorites' type list.
Just use the favorites list.
Provide a hex range/multiple hex ranges.

My personal reasoning was that I'd like to have Insider randomly select from one set of colors (say, pastel selections) while release picks from a different set (neon colors, for example). I'm fine providing those values, but I do like randomizers.

**Comment by johnpapa** [comment]
neat idea, but not something i want to extend at this time
