### ISSUE TITLE
User Settings define for Workspace Settings

### ISSUE THREAD

**Issue by paul-lapczynski** [johnpapa/vscode-peacock#145]
We typically check in our work space settings file.

It would be great to define settings in the User Settings file and point to a particular workspace

`
{
"workspaces": [{"C:\Path\To\Workspace", 
"workbench.colorCustomizations": {...}
}]
}
`

I am not sure if this kind of thing is possible, but it would be a nice feature I think.

**Comment by johnpapa** [comment]
I believe this is a duplication of #7. If not, please let us know.
