### ISSUE TITLE
Save random colour to settings

### ISSUE THREAD

**Issue by spences10** [johnpapa/vscode-peacock#15]
Great extension, thanks @johnpapa 🙏 

Say I generate a random colour and I really want to keep that as the new colour of the workbench, is there a way to extract what's currently selected and add that to the `.vscode` folder or replace any colours that are already there??

```json
{
  "workbench.colorCustomizations": {
    "titleBar.activeBackground": "#663399",
    "titleBar.inactiveBackground": "#663399c9"
  }
}
```

**Comment by spences10** [comment]
Apologies! 

Just realised it creates the `.vscode` file for you!! 🙃 🤦‍♂️

**Comment by johnpapa** [comment]
No worries. This means I need more details in the readme. I’ll add some. Thanks.

**Comment by spences10** [comment]
@johnpapa it looks like on only one repo of mine that I can't generate colours and I don't know why not.

I've tried deleting the `.vscode` folder altogether and starting again and all the extension generates is an empty `colorCustomizations` object :

```json
{
  "workbench.colorCustomizations": {}
}
```

Odd
