### ISSUE TITLE
Allow switching color per project in workspace

### ISSUE THREAD

**Issue by reflog** [johnpapa/vscode-peacock#16]
Thanks for a really great extension! It would be really nice if it could change color depending on the project you currently have a file open from.

**Comment by johnpapa** [comment]
Can you clarify what you mean?

**Comment by reflog** [comment]
The scenario is simple:
I have a workspace with 5 projects inside.
It would be great if Peacock would change the color of Title Bar and the open file tabs with a per-project color, so there is an additional level of distinction, not just between Workspaces, but also between Projects *inside* the workspace.

**Comment by johnpapa** [comment]
ah - this is not on the roadmap right now, but i'll keep this open if someone wants to explore how this could work. would require a lot of refactoring

**Comment by johnpapa** [comment]
im going to close this out - if anyone has thoughts on this, we can always re-open

**Comment by luxaritas** [comment]
I have a multi-root workspace that has many different projects in it - it would be great if I could, say, have a bottom border on the tab colored based on which project it's in. I would find it hard to juggle multiple VSC windows and am often jumping between projects a lot, so the current setup wouldn't work well for me. I could also see this working well for those using monorepos.

**Comment by Clem-** [comment]
If someone knows a VSC Extension that does this, it would be awesome!
