### ISSUE TITLE
2.4.0 version doesn't work - 'dist' folder not found

### ISSUE THREAD

**Issue by ivanolarocca** [johnpapa/vscode-peacock#181]
In the extension folder johnpapa.vscode-peacock-2.4.0 there isn't dist folder, so the extension doesn't work and in vscode console comes out:
`[Extension Host] Here is the error stack:  Error: Cannot find module 'C:\Users\MYNAME\.vscode\extensions\johnpapa.vscode-peacock-2.4.0\dist\extension'...`

For now i revert to 2.3.0 to work

Thanks.

**Comment by johnpapa** [comment]
Could you try uninstalling it and reinstalling it? @ivanolarocca 

If that doesnt work please provide the information the issue template requests, including version, OS, etc. so i can better help you.

Is anyone else seeing this problem? I am not experiencing it and the CI tests on Windows, mac, and Linux do not show it.

**Comment by ivanolarocca** [comment]
> Could you try uninstalling it and reinstalling it? @ivanolarocca
> 
> If that doesnt work please provide the information the issue template requests, including version, OS, etc. so i can better help you.
> 
> Is anyone else seeing this problem? I am not experiencing it and the CI tests on Windows, mac, and Linux do not show it.

Thanks, I had already tried to reinstall. This morning I did it again and everything works. Strange things...
I'm sorry, thank you very much and good day to you.
