### ISSUE TITLE
Add somewhere (in Activity Bar for example) a custom logo for the current project in conjunction with the color 

### ISSUE THREAD

**Issue by pliolis** [johnpapa/vscode-peacock#186]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by johnpapa** [comment]
Neat idea.

I am not aware of a feature that would allow this. If one becomes available or I missed it, let's reopen at that time to discuss
