### ISSUE TITLE
Support a Surprise Me on Startup that only selects from Favorites

### ISSUE THREAD

**Issue by cfjedimaster** [johnpapa/vscode-peacock#188]
**Is your feature request related to a problem? Please describe.**
I want a color assigned automatically, but only from colors I've set to Favorites.

**Describe the solution you'd like**
A new setting based on surpriseMeOnStartup that only selects from Favorites. If you have none, it does nothing. If you have one, it's always that one. 

**Describe alternatives you've considered**
I'd also be happy with a *non* random solution. Basically, given that I've picked 5 colors, I don't want to have to think anymore. Let the first VSC instance be color 1, the second color 2, etc.

**Comment by johnpapa** [comment]
hmmm .. neat idea. what if it had a setting for that on startup if either chooses from favorites or from a random color? 

`surpriseMeOnStartupFromFavoritesOnly` ???

**Comment by cfjedimaster** [comment]
I'd be fine with either. Basically I just didn't want to think about it, but some of the random colors were... omg bad. ;) So I can definitely see me taking 5 minutes to pick 3 favorites and then never thinking about it again.

**Comment by johnpapa** [comment]
yeah, i have felt his pain too ... i dont use the surprise me on startup feature, but i do use surprise me ... and i usually have to cycle through a few to get something i like. i think this could be a good feature.

**Comment by johnpapa** [comment]
This will be released with 2.5.0.

Please try this out by trying the rc in the releases https://github.com/johnpapa/vscode-peacock/releases/tag/2.5.0-rc1

Also added you as a contributor for the idea. Thanks Raymond

**Comment by cfjedimaster** [comment]
First off - thank you *so* much for specifying how to test w/ the VSIX file.

I ran "Add the Recommended Favorites" first.

Then in settings I selected "Surprise Me From Favorites Only" and "Surprise Me on Startup".

On Startup, it is *not* selecting a new color. It is using my last selected favorite color. It seems like "Surprise Me on Startup" is broken now?

**Comment by johnpapa** [comment]
Re-opening so I can investigate

**Comment by johnpapa** [comment]
The way "surprise me on startup" works is that it only applies a new color on startup if you both have the setting checked to `true` and you dont have an existing color already set with Peacock.

The idea was that you may not want the color to change every time it opens if you already have a color set. 

For example, imagine you have a workspace/project where you choose `#ff0`  as your color. Then you have another workspace where you don not have a color and you want to be surprised by a color. Currently this works. The "surprise me on startup" setting is a user setting so every instance of vs code respects it. If the logic were to be changed to surprise on every startup regardless if there was a color already set, then your colors would be overwritten every time.

So it works as designed (and I'll add something to the readme on this).

That all said ... I can see your point. Some options:
1. Leave this as designed so it does not override an existing color
2. If a color exists, prompt the user to change it to a surprise (might be annoying)
3. Store the "surprise me" in a workspace memento. The downside here is that the memento is only stored on this machine for this workspace. Not in settings. This means that every workspace would need a memento (a saved value) for every machine you run it on.

I am leaning to the first option and adding two new actions items:
- Add details to the readme on how this works
- Show an informational message on startup if you choose "surprise me on startup" and there is a color already

FYI - there is a test that checks for this condition ... this was helpful for me to recall :)

```
 1) Surprise me on startup
       when set
         has no effect when color customizations exist:
```

**Comment by johnpapa** [comment]
I'm re-closing the issue, but please try the latest release, which includes the changes I mention above.

**Comment by cfjedimaster** [comment]
Hmm. I guess I'm confused then. If it won't pick a new random color once I've selected one, and the "pick a random one on startup" is the same as me picking one, doesn't that mean "Pick a random on startup" will only work exactly *one* time? 

Oh wow. So I just changed directories in Code and I got a new color. I opened a new window and picked a different folder and it's a new color.

Ok... I think it's working well now!

**Comment by johnpapa** [comment]
> If it won't pick a new random color once I've selected one, and the "pick a random one on startup" is the same as me picking one, doesn't that mean "Pick a random on startup" will only work exactly one time?

yes, it will only work one time *per workspace*

does that make sense?

**Comment by cfjedimaster** [comment]
yep, absolutely now. tbh, I don't think of workspaces but rather directories of my projects.

**Comment by johnpapa** [comment]
me too ... tbh
