### ISSUE TITLE
Idea: Easier means to map colors to remote hosts

### ISSUE THREAD

**Issue by rhencke** [johnpapa/vscode-peacock#189]
When I connect to a remote host using the Remote Development pack, I often set a Peacock color for it, so I can more easily distinguish between different hosts I am connected to (test, staging...)

I currently do this by setting Peacock settings on a temporary workspace, then copying the written settings in the `remote` level configuration, which gets stored on each remote.  (Preferences: Open Remote Settings when connected).

I would love to have a Peacock option similar to the Live Share options, perhaps: 'Peacock: Change Remote Host Color'.  Peacock would then present a list of colors as in 'Peacock: Change to a Favorite Color'.  After color selection, Peacock would write the color selections to the remote settings file, in the same way it would for a Live Share- or workspace-based configuration.

**Comment by johnpapa** [comment]
This is coming  in PR #187

**Comment by johnpapa** [comment]
closed in #187 and #194
