### ISSUE TITLE
not working - not sure what i'm doing wrong

### ISSUE THREAD

**Issue by ormico** [johnpapa/vscode-peacock#19]
This would be really useful to me, but I can't seem to get it to work.
I've installed the plugin and run the command to pick a random color but nothing changes.
I've tried setting it to Angular Red, Random, and some other stuff but nothing changes.
I checked my settings.json and there was no section for Peacock.
I added the following
```
    "peacock.affectedSettings": [
        "activityBar",
        "statusBar",
        "titleBar"
    ]
```

closed and re-opened. Tried again but still nothing.

What can I be doing wrong?
Is there a particular way to run the command and I'm doing it wrong?
I'm just picking it from the drop-down on the command pallet recently used list.

Platform:
Version: 1.31.1 (user setup)
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:20:54.427Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

**Comment by johnpapa** [comment]
Once you have this settings saved , coloring should work. Are you sure the settings file is saved?

**Comment by ormico** [comment]
I've closed and re-opened vs code and the file has the same values so I think it's saved.

here is my entire file

```
{
    "workbench.iconTheme": "material-icon-theme",
    "team.showWelcomeMessage": false,
    "vs-kubernetes": {
        "vs-kubernetes.helm-path": "C:\\Users\\zack.moore\\.vs-kubernetes\\tools\\helm\\windows-amd64\\helm.exe",
        "vs-kubernetes.draft-path": "C:\\Users\\zack.moore\\.vs-kubernetes\\tools\\draft\\windows-amd64\\draft.exe",
        "vs-kubernetes.minikube-path": "C:\\Users\\zack.moore\\.vs-kubernetes\\tools\\minikube\\windows-amd64\\minikube.exe"
    },
    "mssql.connections": [
        {
            "connectionString": "Server=.;Database=test;Trusted_Connection=True;",
            "profileName": "Example",
            "password": ""
        }
    ],
    "files.autoSave": "afterDelay",
    "peacock.affectedSettings": [
        "activityBar",
        "statusBar",
        "titleBar"
    ]
}
```

I'm pressing [ctrl]+[shift]+p. Peacock: Color to Random is at the top of the list. I press enter and nothing happens. I can use the up/down arrow keys to make sure I've selected it but it doesn't make a difference.

**Comment by ormico** [comment]
maybe another plugin is interfering but I don't know which one could.

**Comment by johnpapa** [comment]
After you try to change the color, is your workspace settings file changed? That’s what the command does - it writes to your workspace settings. It’s in .vscode/settings.json

**Comment by ormico** [comment]
oh. does it only work on workspaces? I open plain folders a lot and specific files a lot. I only have a few workspaces and didn't think to try that until you mentioned it.

it did work when I opened a workspace and changed the color.

**Comment by johnpapa** [comment]
A folder should work fine. It would create the file for you if it doesn’t exist.

**Comment by Amerzel** [comment]
I had to explicitly add: 
```
"peacock.affectedSettings": [
    "activityBar",
    "statusBar",
    "titleBar"
]
``` 
to my user settings.json file before the color change would take place.

**Comment by ormico** [comment]
ok, I've got it working in some windows now.
it looks like a bunch of my open windows are not associated with a folder but just have random files open. Those don't work.
But if I right click in a folder and say 'Open in Code' or pick a folder from my recent list on Start menu, those work after I set peacock.affectedSettings.
Also works if I open a workspace file.

**Comment by johnpapa** [comment]
@Amerzel yes, we added this to the readme to help folks recently. I am also working on sensable defaults in a PR

**Comment by NitsanBaleli** [comment]
added 

`
"peacock.affectActivityBar": true,
"peacock.affectStatusBar": true,
"peacock.affectTitleBar": true,
"peacock.elementAdjustments": {
    "activityBar": "lighten"
},
`

as mentioned in the plugin's welcome screen, and now everything works

**Comment by ips138** [comment]
Reporting the same behaviour. 
The default settings didn't get applied. Had to include the affected areas settings then re-start VsCode for extension to work. 
All good now. Thanks.

**Comment by johnpapa** [comment]
Docs are updated.

**Comment by raminjacobson** [comment]
I had the same issue.  Mine was resolved by creating a workspace and adding a folder.  Then the "Peacock: ..." options started appearing in the command palette.

**Comment by ZohaibTafsol** [comment]
Does peacock works with jellyfish theme or not?

**Comment by davidgeri** [comment]
my peacock extension didnt work, when i press f1 and choose change to favorite color, theres a notification said "activating extension" and then nothing happened

**Comment by lancemcmuffin** [comment]
> my peacock extension didnt work, when i press f1 and choose change to favorite color, theres a notification said "activating extension" and then nothing happened

I came here to report the same issue. If I manually copy-paste a settings.json file into my working directory then peacock recognizes it and applies the colors, but anytime I run a peacock command VSCode just says "Activating Extensions..." and then nothing happens

**Comment by davidgeri** [comment]
uninstall your live share extension first and it will work, i have tried it

**Comment by mayckxavier** [comment]
> uninstall your live share extension first and it will work, i have tried it

It worked for me, but I noticed that I need to open a project folder to Peacock allow me to choose a color.
