### ISSUE TITLE
Refactor remote and live share colors from mementos to settings

### ISSUE THREAD

**Issue by johnpapa** [johnpapa/vscode-peacock#193]
Something to think about as a reminder (mostly for me) to consider ...

Some of the color preferences are stored in settings. Some (live share and remote) are stored in mementos. Is this OK? Is there a clear delineation of what goes in each? Or should there be a consolidation?

cc // @lostintangent @egamma @musicfuel

**Comment by johnpapa** [comment]
decided to keep these as mementos.

**Comment by johnpapa** [comment]
Open for discussion

**Comment by johnpapa** [comment]
Some thoughts on this and how colors are stored today ...

## Where to store the colors

Each workspace can be colored by Peacock in its workspace `settings.json` file. This file is shared across every user of the app unless it is included in the `.gitignore` file.

The 5 new colors (Live Share Host and Live Share Guest and Remote WSL, SSH, and Container) colors are stored in mementos. This means the color selections for these apply to every instance of VS Code on the person's computer, unlike the rest of Peacock which applies to a specific user's workspace. 

We could store these 5 colors in mementos, user settings, or workspace settings (in a custom property).  

-Mementos - Currently how it is implemented in the target for 2.5.0. No easy way for the user to see what they have chosen.
-User Settings - This would allow the user to see and easily change the colors for Remote and Live Share colors, in addition to the commands. 
- Workspace settings - This would allow customization of the colors across multiple workspaces. 

I believe the workspace one is a bit overkill. I lean to the User Settings as they are much more visible to the end user and they have the added benefit of making it easy for someone to share their settings across machines.

**Comment by egamma** [comment]
>I lean to the User Settings as they are much more visible

:+1: In general we use mementos for state that is not user configurable and should not be user visible. These peacock colors are configurable and would be better represented as user settings. In fact, I've found it painful that there is no easy way to inspect/reset/change the currently assigned color, I can only define a new one.

**Comment by johnpapa** [comment]
Thanks for the feedback. I am going to take a look at this and see what effort it would take to move from mementos for all 5 of these, to become user settings.
