### ISSUE TITLE
Add tab.activeBorder to color customizations

### ISSUE THREAD

**Issue by avondohren** [johnpapa/vscode-peacock#196]
**Is your feature request related to a problem? Please describe.**
This is not a problem, it's an enhancement.

**Describe the solution you'd like**
Add `tab.activeBorder` to the color customizations. Use the same color as the `activityBar.background`.

**Describe alternatives you've considered**
Adding the customization myself in settings.

**Additional context**
I'm not a TypeScript developer, so I've tried to pull down the codebase but I don't know where to start. I believe that this would be a very easy change if someone had even a beginners level of TypeScript knowledge.

**Comment by johnpapa** [comment]
Is this the effect you are looking for?

![image](https://user-images.githubusercontent.com/1202528/61097787-982a4700-a42a-11e9-92fe-bd465f7e79d2.png)


Notice that when the color os dark it is hard to see it. The border is so think. Even if I make top and bottom affected.

![image](https://user-images.githubusercontent.com/1202528/61097848-ce67c680-a42a-11e9-8034-81e5c9b690a9.png)


Let me know if I understood correctly. 

Love to hear feedback on this or other settings people may be interested in.

**Comment by avondohren** [comment]
Yep! That's what I was thinking. The bottom border line is much more important to me than the top.

I'm the guy that tweeted about doing the custom colors in VS Code this week. This is the main thing that I had been customizing that you didn't cover in Peacock. Now that I've switched over, I'm really liking it. Kinda crazy how similar my approach is with yours. I just hadn't gotten around to automating it yet!

Thanks for taking a look so quickly. Let me know if there's anything I can do on my side to assist.

**Comment by johnpapa** [comment]
Ok, thanks for confirming we're on the same page :)

I'd like to gather some feedback form the community on this first. So if others are interested, they can comment here.

Let's give it some time for folks to chime in ... feel free to point others here

**Comment by avondohren** [comment]
Awesome. Thanks again! No rush from me. Wish I knew TS so I could have contributed myself.

**Comment by johnpapa** [comment]
no worries - this would be fun to do over Twitch. maybe @_clarkio will invite me on :)

**Comment by avondohren** [comment]
That's a great idea! Should be a small enough scope to explain things along the way without making it so long it gets drawn out.

I'd tune in for sure!

**Comment by johnpapa** [comment]
Feedback wanted. Would you like if Peacock gave you the choice of optionally coloring a few select accent borders?

Left side is accented ... right side is without. 

To be clear, this would be a single setting "affectAccentBorders: boolean" and you could turn it on or off. It defaults to off, which means no accents


![image](https://user-images.githubusercontent.com/1202528/61586501-de2a8d80-ab43-11e9-84d2-233443c549f7.png)

**Comment by johnpapa** [comment]
closed in pr #215 for milestone 2.5.0
