### ISSUE TITLE
Idea: Categorize Favorites by Built-in vs Custom

### ISSUE THREAD

**Issue by johnpapa** [johnpapa/vscode-peacock#198]
Consider if we want to make a breaking change to how the favorites are stored such that the built-in and custom favorites are categorized. This would add a prompt for favorites, but would make the list shorter as the user would select from either built in or custom, then choose the color.

Feedback welcome.

The following code will help.

```
  const options = {
    placeHolder: 'Pick a favorite color',
    onDidSelectItem: tryColorWithPeacock()
  };
  let x = [
    { label: 'Built in', description: 'Dark Night --> #000' },
    { label: 'Custom', description: 'Light Day --> #fff' }
  ];
    let y = await vscode.window.showQuickPick(x, options);
```

**Comment by kbd** [comment]
2¢: I would like colors I've added to be separate from the built-ins.

**Comment by johnpapa** [comment]
new features has landed: faves are not written to settings , unless you change them. also, faves thaat are built in are reduced to 8.

this isnt the same as this issue, but it does help reduce settings.

closing this issue as I dont see a good clean way nor the time to attend to original issue here
