### ISSUE TITLE
Peacock commands have no effect on workspace

### ISSUE THREAD

**Issue by accidentaldeveloper** [johnpapa/vscode-peacock#20]
I'm trying out peacock but it does not work on my machine.

Running any peacock command adds the following line to my settings.json:

`    "workbench.colorCustomizations": {},
`

Version: 1.31.1 (user setup)
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:20:54.427Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by ormico** [comment]
ha. i just filled this exact same ticket.

**Comment by flyznex** [comment]
You must add peacock affected setting to your `settings.json` file:
`	"peacock.affectedSettings": [
		"activityBar",
		"statusBar",
		"titleBar"
	],`

**Comment by accidentaldeveloper** [comment]
Thanks @flyznex ! I assumed that it would default to a certain set, which could be customized by specifying `peacock.affectedSettings`. I don't think that was entirely clear from the readme. 

This ambiguity could be resolved by either adding a default or clarifying in the readme. 

@johnpapa How do you feel about defaulting `peacock.affectedSettings` to a certain set?

**Comment by johnpapa** [comment]
I definitely need something in the readme for this for now. Anyone want to make a pull request?

Also - I agree that there needs to be some change to behavior. It’s natural to think it will color something when you choose “change color”. It could default one setting. Or it could prompt you to choose a setting. Or it could set them all. What behavior would you feel is proper?

**Comment by accidentaldeveloper** [comment]
I can make a pull request to the readme.

I think that it should default to `"peacock.affectedSettings": [ "titleBar" ],`. That's the setting that feels most natural to me.

**Comment by accidentaldeveloper** [comment]
PR created: https://github.com/johnpapa/vscode-peacock/pull/21

**Comment by JulianG** [comment]
> I can make a pull request to the readme.
> 
> I think that it should default to `"peacock.affectedSettings": [ "titleBar" ],`. That's the setting that feels most natural to me.

I've created an issue for the default settings (https://github.com/johnpapa/vscode-peacock/issues/23)

**Comment by accidentaldeveloper** [comment]
I just realized that maximizing VS Code in Mac OS hides the title bar. I commonly put each VS Code window in its own Space which means that the colored title bar doesn't provide a benefit (and wouldn't show the changes if it was the default). I have switched to using "activityBar" instead and it's perfect for my needs.

**Comment by johnpapa** [comment]
Awesome. Glad you figured this out!
