### ISSUE TITLE
Remote integration: do not assign a remote color when the workspace already has an assigned color

### ISSUE THREAD

**Issue by egamma** [johnpapa/vscode-peacock#216]
- Change the default remote color for a workspace to `blue`
- Since you want to make the workspace stand out more you assign a custom color `green` to the workspace
- Reopen the remote workspace

-> the workspace is opened with `blue` and not my custom `green`.

The remote integration should not assign the default remote color to a remote workspace, when the remote workspace already has a color.

**Comment by johnpapa** [comment]
Are you saying this is a bug that isn’t happening now or is this in preparation for #217 ?

**Comment by egamma** [comment]
I consider it as a bug. When a user has already configured a peacock color for a remote workspace, then it should not be overwritten. 

Respecting the existing peacock color will also enable that different remote workspaces can have different peacock colors.

Not overwriting a color will also enable #217. Consider a user that is already using remote and peacock  and has configured the peacock color. When a new version of peacock would come out then the customization would be lost.

**Comment by johnpapa** [comment]
I have to try to reproduce this to better understand it. 

Re reading your initial comments it soundscape like once you set a remote color (blue) even if you change it you will always get blue. Is that right? That’s not good.

**Comment by egamma** [comment]
>Re reading your initial comments it soundscape like once you set a remote color (blue) even if you change it you will always get blue. Is that right? That’s not good.

I agree this is not good. You can change the color and it will be honored, but after the next restart you will get the default color again. The PR https://github.com/johnpapa/vscode-peacock/pull/223 fixes this issue.

**Comment by johnpapa** [comment]
Thanks for bearing with me. I'll explore your tests on this too.
