### ISSUE TITLE
Remote integration: Have a default color(s) for remote workspaces?

### ISSUE THREAD

**Issue by egamma** [johnpapa/vscode-peacock#217]
To get a different color for a remote context, the user has to first configure a default color. Rather than having the user to define a default color, the peacock extension should define a default color for remote(s) and make this color available in a user setting.

As described in #216 this default color should only be applied when the workspace has no custom color defined.

**Comment by johnpapa** [comment]
Would you suggest having the remote colors settings each have a default value (each with a different color out of the box)?

Or do you feel there should be three new settings for default colors, one per remote type? 

I assume the idea here is to have the remote have a color with less user action. For example
- user installs Peacock
- they go to remote ssh
- color is set to the default ssh color (new setting?)

**Comment by johnpapa** [comment]
Furthering this discuss considering the pending PR for v3.0.0 #225 , we should revisit this issue.

If we feel peacock should have a default color, this will affect user experience. Peacock would colorize the editor with a default color with no user action. Is this more desirable for users than not coloring and then choosing their own color? If we choose a default color, what is a color that can be most likely to make most users happy (is there one)?

I am hesitant to add default colors - but very open to feedback.

**Comment by johnpapa** [comment]
closing for now and instead documenting it #235

**Comment by egamma** [comment]
👍 the fact that the remote color is now a setting makes this support more discoverable.
