### ISSUE TITLE
Consider alternative name for "affectedSettings"

### ISSUE THREAD

**Issue by accidentaldeveloper** [johnpapa/vscode-peacock#22]
The "settings" are all page elements. The purpose of peacock is to change the color of workspace elements. The settings are simply the means by which peacock accomplishes this goal.

I propose that "affectedSettings" should be named "affectedElements".

```javascript
// Elements that you can choose to color
"peacock.affectedElements": [
    "activityBar",
    "statusBar",
    "titleBar"
  ]
```

**Comment by johnpapa** [comment]
good point. I like this idea and will implement it.

**Comment by johnpapa** [comment]
will be on v0.1.0
