### ISSUE TITLE
"Surprise me on startup" always sets default colors

### ISSUE THREAD

**Issue by kbd** [johnpapa/vscode-peacock#227]
Opening VSCode when `"peacock.surpriseMeOnStartup": true` always creates the default colors instead of surprising me.

Opening into an empty directory:

```
$ ls -a
./  ../
$ rg peacock ~/Library/Application\ Support/Code/User/settings.json
101:    "peacock.surpriseMeOnStartup": true,
102:    "peacock.affectStatusBar": false,
103:    "peacock.affectActivityBar": false,
104:    "peacock.affectAccentBorders": false,
105:    "peacock.affectTabActiveBorder": true,
106:    "peacock.favoriteColors": [
$ code .
$ bat --style=header .vscode/*
File: .vscode/settings.json
{
    "workbench.colorCustomizations": {
        "editor.selectionBackground": "#888",
        "editor.selectionHighlightBackground": "#555",
        "editor.findMatchHighlightBackground": "#2cdd1c65",
        "editorIndentGuide.activeBackground": "#888",
        "titleBar.activeBackground": "#777777",
        "titleBar.inactiveBackground": "#77777799",
        "titleBar.activeForeground": "#e7e7e7",
        "titleBar.inactiveForeground": "#e7e7e799",
        "tab.activeBorder": "#909090"
    }
}
```

Closing VSCode, deleting the `.vscode` directory, and re-opening VSCode results in the same colors being created:

```
$ rm -r .vscode
$ ls -a
./  ../
$ code .
$ bat --style=header .vscode/*
File: .vscode/settings.json
{
    "workbench.colorCustomizations": {
        "editor.selectionBackground": "#888",
        "editor.selectionHighlightBackground": "#555",
        "editor.findMatchHighlightBackground": "#2cdd1c65",
        "editorIndentGuide.activeBackground": "#888",
        "titleBar.activeBackground": "#777777",
        "titleBar.inactiveBackground": "#77777799",
        "titleBar.activeForeground": "#e7e7e7",
        "titleBar.inactiveForeground": "#e7e7e799",
        "tab.activeBorder": "#909090"
    }
}
```

**Comment by johnpapa** [comment]
What version of vscode and peacock?

Can you share reproducible steps?

**Comment by kbd** [comment]
> What version of vscode and peacock?

Apologies, should have provided. Since vscode and extensions are kept to date automatically (I made sure to restart vscode before reporting) I always assume "current version". Work computer (reported from) has vscode 1.36.1 and Peacock 2.5.2.

However, my home computer I'm on now, with all the same versions and settings including vscode config (which is source controlled and shared between computers), doesn't have the reported behavior!

> Can you share reproducible steps?

In the report give exactly all the commands I ran.

> When you say "default colors", what are you referring to (Peacock doesnt have default colors)?

The colors I included in the report. Those appear to be the colors vscode has by default whether or not Peacock is enabled.

**Comment by johnpapa** [comment]
Ok. Thanks. There are no defaults so I suspect your issue was the one reported in #226

I’d 2.5.2 fixed it then I think we can close now. 

Thanks!!

**Comment by kbd** [comment]
> [If] 2.5.2 fixed it then I think we can close now.

Yeah like I said, my work computer is on 2.5.2 and has the behavior I described. I can't say why my work computer has the reported behavior but my home computer doesn't. In any case, if the logic is going to be refactored anyway I'm happy to test and report back when the next version is released.

> Thanks!!

Thank *you* for Peacock!

**Comment by kbd** [comment]
Quick follow up on this, since my home computer doesn't repro the issue in #226.

There are two separate issues:

* Peacock always creates "default" colors even when "surprise me on startup" is disabled.
* "Surprise me on startup" always creates default colors when set.

Since my home computer doesn't repro the first issue, I can show that "Surprise me on startup" isn't creating the workspace settings at all:

```
$ rg peacock ~/Library/Application\ Support/Code/User/settings.json
101:    "peacock.surpriseMeOnStartup": true,
102:    "peacock.affectStatusBar": false,
103:    "peacock.affectActivityBar": false,
104:    "peacock.affectAccentBorders": false,
105:    "peacock.affectTabActiveBorder": true,
106:    "peacock.favoriteColors": [
$ ls -a
./  ../
$ code .
$ ls -a
./  ../
```

In fact, "Surprise me on startup" has never worked for me (on either computer), and I've been using Peacock basically since it was released.

**Comment by johnpapa** [comment]
Let’s close this one and reopen one for surprise me not working for you. Ok?

I think I recall some folks having issues with surprise me at one point. I’d have to dig thru the old issues to see what he solution was. But let’s do that in another issue since this was about defaults.
