### ISSUE TITLE
"Surprise me on startup" not working

### ISSUE THREAD

**Issue by kbd** [johnpapa/vscode-peacock#228]
Versions:
- Mac: 10.14.5
- vscode: 1.36.1
- Peacock: 2.5.2

Peacock config:

```
$ rg peacock ~/Library/Application\ Support/Code/User/settings.json
101:    "peacock.surpriseMeOnStartup": true,
102:    "peacock.affectStatusBar": false,
103:    "peacock.affectActivityBar": false,
104:    "peacock.affectAccentBorders": false,
105:    "peacock.affectTabActiveBorder": true,
106:    "peacock.favoriteColors": [
```

Steps taken: Start vscode in an empty directory. Random colors are not set and no workspace config is created:

```
$ ls -a
./  ../
$ code .
$ ls -a
./  ../
```

Please let me know what else I can do to help diagnose. Thanks again for Peacock.

**Comment by johnpapa** [comment]
Thanks for the feedback. Peacock only works if there is a workspace open, because it needs the settings.json file to work. I believe this is the situation you are in. Please let me know if I am incorrect.

If this is your situation, we can close this. But if this is not clear in the Readme, then I'd appreciate any ideas for readme additions.

**Comment by kbd** [comment]
I thought a workspace in vscode is simply a directory containing a `.vscode` subdirectory, and that the behavior of "surprise me on startup" would create a `.vscode` directory with color settings if none existed.

Apparently I still don't understand, because I tried creating a workspace with no color customizations using "File -> Save Workspace As", then reopening the workspace, and no color customizations were created by Peacock. I also tried creating a `.vscode/settings.json` file via "Preferences: Open Workspace Settings" and saving one (non-color) setting, then re-opening vscode in that dir, and still no color customizations were created by Peacock.

So, it's totally possible Peacock is behaving as expected and I don't know how to even create the conditions that would let it do what it's supposed to :-/

**Comment by johnpapa** [comment]
When in a workspace, have you tried using the peacock commands such as "choose a favorite" ?

**Comment by kbd** [comment]
Just tried "Surprise me with a random color" in both my directory with the `.code-workspace` file and in the one with the basic `.vscode/settings.json` file. In both cases, it correctly added the randomly generated colors, first to the `.code-workspace` file and then to the `.vscode/settings.json` file. "Surprise me with a random color" also works in a completely empty directory and creates a new `.vscode/settings.json` file with the random colors applied.

**Comment by johnpapa** [comment]
I'll try 2.5.2.

Just to see what happens, can you try 3.0.0-rc.2? https://github.com/johnpapa/vscode-peacock/releases/tag/v3.0.0-rc.2

**Comment by kbd** [comment]
Installed 3.0.0-rc2. Here's the behavior I get now:

Empty directory with `surpriseMeOnStartup: true` creates random color customizations:

```
$ ls -a
./  ../
$ code .
$ bat --style=header,numbers .vscode/*
     File: .vscode/settings.json
   1 {
   2     "workbench.colorCustomizations": {
   3         "editor.selectionBackground": "#888",
   4         "editor.selectionHighlightBackground": "#555",
   5         "editor.findMatchHighlightBackground": "#2cdd1c65",
   6         "editorIndentGuide.activeBackground": "#888",
   7         "titleBar.activeBackground": "#4409cd",
   8         "titleBar.inactiveBackground": "#4409cd99",
   9         "titleBar.activeForeground": "#e7e7e7",
  10         "titleBar.inactiveForeground": "#e7e7e799",
  11         "tab.activeBorder": "#5814f5"
  12     },
  13     "peacock.color": "#4409cd"
  14 }
$ rg peacock ~/Library/Application\ Support/Code/User/settings.json
101:    "peacock.surpriseMeOnStartup": true,
102:    "peacock.affectStatusBar": false,
103:    "peacock.affectActivityBar": false,
104:    "peacock.affectAccentBorders": false,
105:    "peacock.affectTabActiveBorder": true,
106:    "peacock.favoriteColors": [
```

Turning `surpriseMeOnStartup` to `false` and opening vscode in an empty directory still creates a `.vscode/settings.json` file with these settings (which are consistent between repeated opening-in-an-empty-directory's):

```
$ ls -a
./  ../
$ code .
$ bat --style=header,numbers .vscode/*
     File: .vscode/settings.json
   1 {
   2     "workbench.colorCustomizations": {
   3         "editor.selectionBackground": "#888",
   4         "editor.selectionHighlightBackground": "#555",
   5         "editor.findMatchHighlightBackground": "#2cdd1c65",
   6         "editorIndentGuide.activeBackground": "#888"
   7     }
   8 }
$ rg peacock ~/Library/Application\ Support/Code/User/settings.json
101:    "peacock.surpriseMeOnStartup": false,
102:    "peacock.affectStatusBar": false,
103:    "peacock.affectActivityBar": false,
104:    "peacock.affectAccentBorders": false,
105:    "peacock.affectTabActiveBorder": true,
106:    "peacock.favoriteColors": [
```

I also tried creating a new workspace. I first opened vscode with `surpriseMeOnStartup` set to `false`, then saved a new workspace, then set `surpriseMeOnStartup` set to `true` in another window, then re-opened the workspace and it correctly added a random color to the workspace (but it did (incorrectly?) create those default colors in `.vscode/settings.json` as previously shown):

```
$ ls -a
./  ../
$ code .
$ ls -a
./  ../  .vscode/  pc.code-workspace
$ code pc.code-workspace
$ bat --style=header,numbers .vscode/* pc.code-workspace
     File: .vscode/settings.json
   1 {
   2     "workbench.colorCustomizations": {
   3         "editor.selectionBackground": "#888",
   4         "editor.selectionHighlightBackground": "#555",
   5         "editor.findMatchHighlightBackground": "#2cdd1c65",
   6         "editorIndentGuide.activeBackground": "#888"
   7     }
   8 }
     File: pc.code-workspace
   1 {
   2     "folders": [
   3         {
   4             "path": "."
   5         }
   6     ],
   7     "settings": {
   8         "workbench.colorCustomizations": {
   9             "editor.selectionBackground": "#888",
  10             "editor.selectionHighlightBackground": "#555",
  11             "editor.findMatchHighlightBackground": "#2cdd1c65",
  12             "editorIndentGuide.activeBackground": "#888",
  13             "titleBar.activeBackground": "#29153c",
  14             "titleBar.inactiveBackground": "#29153c99",
  15             "titleBar.activeForeground": "#e7e7e7",
  16             "titleBar.inactiveForeground": "#e7e7e799",
  17             "tab.activeBorder": "#432262"
  18         },
  19         "peacock.color": "#29153c"
  20     }
  21 }
```

Finally, warning: the new version wiped my previously saved colors for one of my workspaces (normal `.vscode` workspace not `.code-workspace` workspace), but I haven't been able to reproduce that by setting `surpriseMeOnStartup` to either value and re-opening vscode after setting back to my favorite color for that workspace.

**Comment by johnpapa** [comment]
> Installed 3.0.0-rc2. Here's the behavior I get now:
> 
> Empty directory with `surpriseMeOnStartup: true` creates random color customizations:
> 
> ```
> $ ls -a
> ./  ../
> $ code .
> $ bat --style=header,numbers .vscode/*
>      File: .vscode/settings.json
>    1 {
>    2     "workbench.colorCustomizations": {
>    3         "editor.selectionBackground": "#888",
>    4         "editor.selectionHighlightBackground": "#555",
>    5         "editor.findMatchHighlightBackground": "#2cdd1c65",
>    6         "editorIndentGuide.activeBackground": "#888",
>    7         "titleBar.activeBackground": "#4409cd",
>    8         "titleBar.inactiveBackground": "#4409cd99",
>    9         "titleBar.activeForeground": "#e7e7e7",
>   10         "titleBar.inactiveForeground": "#e7e7e799",
>   11         "tab.activeBorder": "#5814f5"
>   12     },
>   13     "peacock.color": "#4409cd"
>   14 }
> $ rg peacock ~/Library/Application\ Support/Code/User/settings.json
> 101:    "peacock.surpriseMeOnStartup": true,
> 102:    "peacock.affectStatusBar": false,
> 103:    "peacock.affectActivityBar": false,
> 104:    "peacock.affectAccentBorders": false,
> 105:    "peacock.affectTabActiveBorder": true,
> 106:    "peacock.favoriteColors": [
> ```
> 

[papa] - The above is correct behavior (tho something else must be adding `editor.selectionBackground` and its similar settings as peacock doesnt use those)

> Turning `surpriseMeOnStartup` to `false` and opening vscode in an empty directory still creates a `.vscode/settings.json` file with these settings (which are consistent between repeated opening-in-an-empty-directory's):
> 
> ```
> $ ls -a
> ./  ../
> $ code .
> $ bat --style=header,numbers .vscode/*
>      File: .vscode/settings.json
>    1 {
>    2     "workbench.colorCustomizations": {
>    3         "editor.selectionBackground": "#888",
>    4         "editor.selectionHighlightBackground": "#555",
>    5         "editor.findMatchHighlightBackground": "#2cdd1c65",
>    6         "editorIndentGuide.activeBackground": "#888"
>    7     }
>    8 }
> $ rg peacock ~/Library/Application\ Support/Code/User/settings.json
> 101:    "peacock.surpriseMeOnStartup": false,
> 102:    "peacock.affectStatusBar": false,
> 103:    "peacock.affectActivityBar": false,
> 104:    "peacock.affectAccentBorders": false,
> 105:    "peacock.affectTabActiveBorder": true,
> 106:    "peacock.favoriteColors": [
> ```
> 

[papa] - The above is correct behavior. No colors will be set if this is off. But again, something else must be adding `editor.selectionBackground` and its similar settings as peacock doesnt use those.



> I also tried creating a new workspace. I first opened vscode with `surpriseMeOnStartup` set to `false`, then saved a new workspace, then set `surpriseMeOnStartup` set to `true` in another window, then re-opened the workspace and it correctly added a random color to the workspace (but it did (incorrectly?) create those default colors in `.vscode/settings.json` as previously shown):
> 
> ```
> $ ls -a
> ./  ../
> $ code .
> $ ls -a
> ./  ../  .vscode/  pc.code-workspace
> $ code pc.code-workspace
> $ bat --style=header,numbers .vscode/* pc.code-workspace
>      File: .vscode/settings.json
>    1 {
>    2     "workbench.colorCustomizations": {
>    3         "editor.selectionBackground": "#888",
>    4         "editor.selectionHighlightBackground": "#555",
>    5         "editor.findMatchHighlightBackground": "#2cdd1c65",
>    6         "editorIndentGuide.activeBackground": "#888"
>    7     }
>    8 }
>      File: pc.code-workspace
>    1 {
>    2     "folders": [
>    3         {
>    4             "path": "."
>    5         }
>    6     ],
>    7     "settings": {
>    8         "workbench.colorCustomizations": {
>    9             "editor.selectionBackground": "#888",
>   10             "editor.selectionHighlightBackground": "#555",
>   11             "editor.findMatchHighlightBackground": "#2cdd1c65",
>   12             "editorIndentGuide.activeBackground": "#888",
>   13             "titleBar.activeBackground": "#29153c",
>   14             "titleBar.inactiveBackground": "#29153c99",
>   15             "titleBar.activeForeground": "#e7e7e7",
>   16             "titleBar.inactiveForeground": "#e7e7e799",
>   17             "tab.activeBorder": "#432262"
>   18         },
>   19         "peacock.color": "#29153c"
>   20     }
>   21 }
> ```
> 

> Finally, warning: the new version wiped my previously saved colors for one of my workspaces (normal `.vscode` workspace not `.code-workspace` workspace), but I haven't been able to reproduce that by setting `surpriseMeOnStartup` to either value and re-opening vscode after setting back to my favorite color for that workspace.

[papa] - "the new version wiped my previously saved colors for one of my workspaces " - this is not good. I'll look into this and open a new issue if I can repro it. It is easier to separate the issues

[papa] - I'm not sure what code-workspace is.

[papa] -  It sounds like 3.0.0 is working for you with surprise me on startup. I'll look further at 2.5.2, but 3.0.0 is jus a few days away, so that may be the way to go.

**Comment by kbd** [comment]
> The above is correct behavior. No colors will be set if this is off. But again, something else must be adding editor.selectionBackground and its similar settings as peacock doesnt use those.

Except those settings only get saved when Peacock (3.0) is installed. So Peacock is causing not-its-settings to be saved even when `surpriseMeOnStartup` is `false`, which is a problem.

> I'm not sure what code-workspace is.

That's the type of file vscode creates when you do "File -> Save Workspace As".

> It sounds like 3.0.0 is working for you with surprise me on startup.

Yeah, "surprise me on startup" behaves as expected in 3.0, but 3.0 is causing `.vscode/settings.json` to be created even if "surprise me on startup" is false, which 2.5.2 *doesn't* do.

**Comment by johnpapa** [comment]
Moving this to a new issue. It is too difficult to track the 3 here.

1. Surprise me not working is being closed 

2. writing extra settings is moving to #229

3. "new version wiped my favorites" - if this is happening, please open a new issue for this with details.= so i can investigate.
