### ISSUE TITLE
Initialise peacock.affectedSettings to ['titleBar'] upon activation

### ISSUE THREAD

**Issue by JulianG** [johnpapa/vscode-peacock#23]
As suggested by @accidentaldeveloper in https://github.com/johnpapa/vscode-peacock/issues/20#issuecomment-466859661

I think it would be safe to initialise to
```
 "peacock.affectedSettings": [
    "titleBar"
  ]
```
within the `activate` function.

**Comment by JulianG** [comment]
I made a PR: https://github.com/johnpapa/vscode-peacock/pull/24

**Comment by johnpapa** [comment]
coming in v0.1.0
