### ISSUE TITLE
Add one or (some) peacock commands to modify the "affectedSettings"

### ISSUE THREAD

**Issue by JulianG** [johnpapa/vscode-peacock#25]
I think we can add one or a few peacock commands to let the user specify which settings to affect.

Peacock: Affect Title Bar [Yes/No]
Peacock: Affect Status Bar [Yes/No]
Peacock: Affect Activity Bar [Yes/No]

Example:

<img width="327" alt="screen shot 2019-02-25 at 07 11 26" src="https://user-images.githubusercontent.com/237818/53320165-b30d7c00-38cc-11e9-9b63-509a1675d178.png">

then:

<img width="150" alt="screen shot 2019-02-25 at 07 11 47" src="https://user-images.githubusercontent.com/237818/53320174-b6a10300-38cc-11e9-9714-28a62145eb95.png">

or maybe something like this?

<img width="271" alt="screen shot 2019-02-25 at 15 41 34" src="https://user-images.githubusercontent.com/237818/53348932-ed4e3c00-3913-11e9-826f-a402629fdf36.png">

**Comment by johnpapa** [comment]
I'm concerned with adding too many menu commands. This seems more suited to the settings file. Is that not working?

**Comment by johnpapa** [comment]
i like the idea, and thanks for sharing it. i've decided against adding commands to set settings since it's fairly conventional to use the existing settings editor.

i'll keep this in mind for future tho

thank!
