### ISSUE TITLE
Launching extension clears all color settings

### ISSUE THREAD

**Issue by Nibblesh** [johnpapa/vscode-peacock#258]
**Versions (please complete the following information):**

VS Code Version: 1.37.0
Commit: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
Date: 2019-08-08T01:24:14.598Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.0.0-23-generic
Peacock Version 3.1.0

**Describe the bug**
Extension clears settings.json workbench.colorCustomizations on launch

**To Reproduce**

Launch VS Code.
project relative .vscode/settings.json is altered by extension

**Expected behavior**
Extension shouldn't remove the color customisations.

**Screenshots**

![Peek 2019-08-16 11-00](https://user-images.githubusercontent.com/9124852/63136394-20e16780-c015-11e9-9bf2-5e55ad33406a.gif)

**Comment by johnpapa** [comment]
There was a breaking change in 3.0 where Peacock now relies on a setting for `peacock.color`. If this is missing, it tries to determine what it is. If it fails to do so, Peacock will remove the colors.  This change was necessary - and I try to make the migration work. But it seems to only work if you go from 2.5+ to 3.0+. if you had < 2.5, it cannot figure out the migration. https://papapeacockstorage.z13.web.core.windows.net/changelog/#_3-0-0

You can get it back by setting the color through any of the menu options, such as "enter a color"

I will update the docs and changelog to explain this better.
