### ISSUE TITLE
It seems that Peacock 3.1.1 not compatible with vscode 1.37.1 

### ISSUE THREAD

**Issue by leon0n** [johnpapa/vscode-peacock#264]
**Versions (please complete the following information):**

- OS: [e.g. ubuntu 18.04]
- VS Code version [e.g. 1.37.1]
- Peacock Version [e.g. 3.1.1]

**Describe the bug**
after the installation, i can't find any commands Peacock.xxx

**Screenshots**
![2019-08-21 11-22-39 的屏幕截图](https://user-images.githubusercontent.com/28854034/63400443-6b445900-c406-11e9-886f-7d7e3e7e34a5.png)

**Additional context**

**Comment by leon0n** [comment]
![2019-08-21 11-22-39 的屏幕截图](https://user-images.githubusercontent.com/28854034/63400466-7d25fc00-c406-11e9-97c3-a697f8dbe424.png)

**Comment by johnpapa** [comment]
Peacock commands will be disabled (except the documentation command) if a workspace cannot be found.

I'll add this to the docs shortly.

Please confirm this is your scenario.

**Comment by leon0n** [comment]
Thanks for your response.
As you suggested, after opening a workspace, the Peacock tool can be used.
thank you :)

**Comment by johnpapa** [comment]
no worries.

I just added some notes to the docs on this. it will be published soon.
