### ISSUE TITLE
Add a Changelog

### ISSUE THREAD

**Issue by kmf** [johnpapa/vscode-peacock#267]
Would be awesome.

**Comment by johnpapa** [comment]
There is a changelog in the docs/guide here https://peacockcode.dev

**Comment by kmf** [comment]
was more referring to this ....
https://code.visualstudio.com/docs/editor/extension-gallery#_extension-details

**Comment by johnpapa** [comment]
Ah. Yeah they read the actual file in the root. I just added a placeholder for it to redirect folks. Will appear in next published release. But you can see the file in master now
