### ISSUE TITLE
settings.json is modified (without any prompt) when opening a project

### ISSUE THREAD

**Issue by MrCroft** [johnpapa/vscode-peacock#269]
**Versions (please complete the following information):**

- OS: Mac OS Mojave / Windows 10 Pro
- VS Code version: 1.37.1
- Peacock Version: 3.1.5

**Describe the bug**
For some projects I have a custom (manually set) color scheme. When opening that project in VSCode, Peacock changes the `workbench.colorCustomizations` object.
See attached screenshot: **Left side** is what I had before Peacock changed the file; **Right side** is what it became when opening the project, after Peacock modified the file (without me  running anything Peacock related in the command palette or accepting any prompt).

**To Reproduce**

1. In a project of your choice, go in `.vscode/settings.json` and paste the following:
```
{
  // Overrides colors from the currently selected color theme.
  "workbench.colorCustomizations": {
    "tab.activeBorder": "#6D91CD",
    "tab.activeBackground": "#233354",
    "statusBar.background": "#233354",
    "statusBar.foreground": "#ffffff"
  }
}
```
and save  the file.
2. Either hit "Cmd + R" (or whatever custom shortcut you have for "reload") **OR** Quit VSCode and reopen it (it should open with the same project; if not, then go to File -> Open and pick that project folder)
3. Notice that `.vscode/settings.json` is modified and it now looks like this:
```
{
  // Overrides colors from the currently selected color theme.
  "workbench.colorCustomizations": {
    "tab.activeBackground": "#233354",
    "activityBar.background": "#324978",
    "activityBar.foreground": "#e7e7e7",
    "activityBar.inactiveForeground": "#e7e7e799",
    "activityBarBadge.background": "#16090e",
    "activityBarBadge.foreground": "#e7e7e7",
    "titleBar.activeBackground": "#233354",
    "titleBar.inactiveBackground": "#23335499",
    "titleBar.activeForeground": "#e7e7e7",
    "titleBar.inactiveForeground": "#e7e7e799",
    "statusBar.background": "#233354",
    "statusBarItem.hoverBackground": "#324978",
    "statusBar.foreground": "#e7e7e7"
  },
  "peacock.color": "#233354"
}
```
affecting more colors than I wanted.
4. What is even stranger is that, after clicking "Revert" on the `settings.json` file in the Git pane, then the file is modified and looks like this:
```
{
  // Overrides colors from the currently selected color theme.
  "workbench.colorCustomizations": {
    "tab.activeBackground": "#233354"
  }
}
```
probably Peacock changes it again, but differently this time.
And I have to hit "Revert" a second time to get the original file.

**Expected behavior**
Existing workbench color scheme (whether set by Peacock or otherwise) shouldn't be modified when opening the project.

**Screenshots**
![image](https://user-images.githubusercontent.com/2809154/63788719-9fd07d00-c8fe-11e9-9ce7-31d3ecd36fa2.png)

**Additional context**
"Surprise me on startup" option is not checked. And I have the Peacock default settings, haven't changed any Peacock setting after installation.

**Comment by johnpapa** [comment]
Thanks for reporting. Peacock used to use the statusbar, titlebar, and activitybar background settings to determine the color. In v3 this has changed, but to migrate the 250k users it checks if those settings are set in workspace , and if so, it colorizes using them. In your case you have a custom statusbar background color. So peacock is using that as the color to use. 

So what can you do? If you want to use Peacock, you can disable the affected elements for the titlebar and activity bar. That will get you to where you are now.

THanks.
