### ISSUE TITLE
Keep original foreground colour

### ISSUE THREAD

**Issue by mrvkino** [johnpapa/vscode-peacock#27]
Could it be possible to keep the foreground colour (activity bar, titlebar and status bar) of the user theme by default?

I put background colour that doesn't fit with my theme (one dark pro) and the default white foreground colour is a bit jarring and I have to edit the config every time.

It could be an override of the default behaviour for the foreground color selection. Or change the default foreground if the contrast is too low.

Thanks

**Comment by johnpapa** [comment]
Thanks for the feedback. The current algorithm uses white or black foreground based on the brightness and contrast of the background color. That's why you see white in your case. 

Your best current option is to go into `vscode/settings.json` and override the foreground to what you want.

If you have other ideas for making this easier, please share

**Comment by mrvkino** [comment]
I tried to test my idea on a fork of the project, but I could not start the extension in debug mode because of weird error such as:

```log
Cannot find module 'vscode'.ts(2307)
Property 'values' does not exist on type 'ObjectConstructor'.ts(2339)
Parameter 'setting' implicitly has an 'any' type.ts(7006)
Property 'includes' does not exist on type 'string[]'.ts(2339)
```

Not sure why I see this.

But the idea I was thinking was looking at the Foreground luminance with the same equation used in "invertColor". From there, generate a random colour with the luminance in the opposite range (if foreground is light create a dark background). Also, making sure the luminance difference between the foreground and the background is a least 69 (based on the threshold of 186 in the "invertColor" function).

The other option I was looking, is if the luminance of the foreground is different enough from the background we can keep it, else we change it to the light or dark option.

Any of the behaviour could be enabled with a setting.

**Comment by johnpapa** [comment]
I think the simplest way to do this if it is automated is to just have a setting that says `peacock.keepForegroundColor` ... and the logic in the extension would check that boolean value and ignore foreground if it is selected.

this may clash with many colors of course 

I'm not sure I want to include this at this time. But open to hearing feedback from anyone interested.

**Comment by johnpapa** [comment]
Moving @musicfuel comments to this issue as they are relevant

> ... I propose we add that flag to settings ... as a means to override the default Peacock behavior. By using the keepForegroundColor the user takes matters into his or her own hands and Peacock should only adjust backgrounds.

I'm open to this if someone wants to map out how this would work.

**Comment by musicfuel** [comment]
I'll go ahead and propose how I see this working.

* A boolean setting of `peacock.keepForegroundColor` will be added as named by @johnpapa above. It will default to **false**.
* When set to **false**, the extension will colorize the foreground color of all affected elements based on the relative brightness of the selected or entered color.
* When set to **true**, the extension will _not_ colorize the foreground of any of the affected elements and will only alter the background.
  * It is understood that there can be contrast issues and that is the responsibility of the end user to accept or correct.
  * None of the `workspace.colorCustomization` styles regarding foreground will be set and neither will they be cleared to avoid the case that the user is controlling the foreground through them manually or another extension.
* Tests will need to be added to the Foreground Color suite to ensure that the flag is honored correctly.

**Comment by johnpapa** [comment]
Sounds good. How will this affect the default foreground colors in the enums.ts ?

**Comment by musicfuel** [comment]
I think those stay as is and this work is likely handled in configuration.ts as part of preparing the colors to simply not use them when this flag is set. More of the work would be to alter the setting/clearing of the different color customizations in that file.

**Comment by johnpapa** [comment]
Yeah - and if this is set, to true, then the defaults are ignored and the workspace settings must not write out foreground colors.

## Scenario 1: no workspace settings exist

1. user sets `keepForegroundColor` to `true`
2. user chooses "surprise me" for a color
3. all background colors are written to the workspace, but not the foreground ones

## Scenario 2: workspace settings exist

1. user sets `keepForegroundColor` to `true`
2. user chooses "surprise me" for a color
3. all workspace color settings are wiped
4. all background colors are written to the workspace, but not the foreground ones


Currently the logic wipes the settings and recreates them each time. Thus, I think this won't require much logic change.

What do you think?

**Comment by musicfuel** [comment]
I think that sounds right. The only difference I had in mind was in Scenario 2, I was thinking of not wiping all the settings and only the background ones. This would allow for the case where the user is managing the foreground already using that method....that said, I think I am complicating it too much. I mean, who would just manage the foreground color of the workspace using this method?

I like it how you've got it outlined

**Comment by johnpapa** [comment]
OK - I'll start work on this PR as it's probably the last big change before I publish v1

**Comment by johnpapa** [comment]
added to v0.7.0
