### ISSUE TITLE
Peacock doesn't color with a workspace setting when opening in Visual Studio Code Remote Development

### ISSUE THREAD

**Issue by damccull** [johnpapa/vscode-peacock#272]
**Versions (please complete the following information):**

- OS: Windows 10 1903
- VS Code version 1.37.1
- Peacock Version 3.1.5

**Describe the bug**
When building the docker container for remote development, then opening the workspace file on the remote container, it clears the `workbench.colorCustomizations` key from the `.workspace` file's `settings` section.

**To Reproduce**
Install VScode, docker, peacock and create a workspace
Set a peacock color with the command palette commands
Configure to use remote development on a docker image
Open in remote development (No color displayed because it's not open in workspace)
VS Code prompts you to open the workspace file instead, click OK and do it
No colors appear, but checking the workspace file shows the `workbench.colorCustomizations` key is gone, though peacock.color still remains.

**Expected behavior**
As defined in the documentation when lacking a peacock.remotecolor, the color should be set

**Comment by damccull** [comment]
FYI this seems to work fine with the .remoteColor key.

**Comment by johnpapa** [comment]
Yes, this works as intended. Let me explain ... the `remoteColor` defines the color that will be used while in a remote environment. [Read here for more details in the docs](https://papapeacockstorage.z13.web.core.windows.net/guide/#remote-development-integration)

Thanks for using Peacock !
