### ISSUE TITLE
F1 Commands gone (except for one)

### ISSUE THREAD

**Issue by cfjedimaster** [johnpapa/vscode-peacock#276]
**Versions (please complete the following information):**

- OS: Windows
- VS Code version: 1.39.0-insider
- Peacock Version: 3.1.5

**Describe the bug**
When opening the command palette and typing "Peacock",  I no longer get multiple commands. Instead I just get one:

![image](https://user-images.githubusercontent.com/393660/64434092-6ed21400-d085-11e9-8095-d63ce9e0b0f7.png)

**To Reproduce**
Open command palette and type "peac"

**Expected behavior**
More commands. :)

**Comment by cfjedimaster** [comment]
And nevermind. A full restart of VSC fixed it. Surprised though that it seemed to "kinda" work.

**Comment by sillygwailo** [comment]
From the FAQ:

> ### Peacock commands are not appearing
> Peacock only works if a workspace is open in Visual Studio Code because it needs the settings.json file to work. When it is not in a workspace, all commands are hidden and disabled except for the "Peacock: Open Documentation" command.

Not saying that's obvious, as I spent 20 minutes spinning my wheels and eventually getting it to work by opening a folder in Visual Studio Code.

**Comment by cfjedimaster** [comment]
Hmmm. I am *mostly* sure I had a folder open but I could be wrong too. Either way, thanks. :)

**Comment by johnpapa** [comment]
sounds good. closing
