### ISSUE TITLE
Peacock installed but no commands available

### ISSUE THREAD

**Issue by serdar** [johnpapa/vscode-peacock#277]
**Versions (please complete the following information):**

- OS: Windows 10 Pro (1903)
- VS Code version: 1.38.1
- Peacock Version: 3.1.5

Installed Peacock extension using VS Code Extension marketplace. Reloaded once install succeeded. Expected additional Peacock commands to be listed in command palette, but only one was available ("Open the documentation").

**To Reproduce**
1. Hit CTRL-SHIFT-P to bring up command palette.
2. Start entering Peacock to see available commands
3. See error

**Expected behavior**
Additional commands to be listed.

**Screenshots**
![image](https://user-images.githubusercontent.com/5574/65130632-2af5ec00-da41-11e9-9d9a-3b10b19c0baf.png)

**Additional context**
n/a

**Comment by johnpapa** [comment]
The docs explain that a workspace must be open for Peacock to work. Please check the FAQ
