### ISSUE TITLE
Add color indicator to "Window" menu.

### ISSUE THREAD

**Issue by NikTJ777** [johnpapa/vscode-peacock#281]
**Is your feature request related to a problem? Please describe.**
No - it is just a request for an additional visual cue to the interface

**Describe the solution you'd like**
I would like to see a color strip associated with each entry on the global "Window" menu - such that the color in the Window menu matches the color selected for the workspace open in that window.

The color could be a simple square or dot at the beginning or end of the entry - or even a background color for the entire entry itself

**Describe alternatives you've considered**
As indicated above, I think a colored dot or square immediately before each item would be best - but setting the background color of each entry would also be acceptable

**Additional context**
I can create a mock-up from a screenshot if that would help.

**Comment by johnpapa** [comment]
I'd love to do this, but unless the API for code has changed, I do not see how it can be done. Do you have some ideas?

**Comment by NikTJ777** [comment]
Not at this stage, since I haven't looked at the code at all.

I can look over the weekend - but I have basically zero knowledge of the VS Code APIs.

**Comment by johnpapa** [comment]
I'll close this for now. But if this feature opens up, I'm very interested.
