### ISSUE TITLE
Store workspace color in version controlled `./vscode/settings.json` without impacting others

### ISSUE THREAD

**Issue by tsimbalar** [johnpapa/vscode-peacock#282]
Thanks a lot for this extension, it turned out to be very useful for our multi-repo project 👍 

**Is your feature request related to a problem? Please describe.**
I have installed the `peacock` extensions and set a color for the multiple projects/repos we work on in my company. 
This saved the color in `./vscode/settings.json` in the projects , and we happen to share those files in version control (to share some of the IDE behavior regarding formatting and other things).

When my colleagues checked out the project, their VS Code was colored like mine, even though they don't have the `peacock` extension installed, and that felt a bit intrusive.

**Describe the solution you'd like**
What I'd like is that the `peacock` theme / color is applied **only** if the user has the `peacock` extension installed, ideally with an option to decline that new color.

Another appropriate option would be to not store the "per-workspace" colors in the `./vscode/settings.json` file and instead globally on the machine (i.e. "personal settings" vs project/team-shared settings

**Comment by johnpapa** [comment]
> What I'd like is that the peacock theme / color is applied only if the user has the peacock extension installed, ideally with an option to decline that new color.

I'm not sure the code API would support this. It is an interesting idea ... if there was a way the intercept Code before it colorizes to check if the extension was installed, it could be done. But there is no API for that.

> Another appropriate option would be to not store the "per-workspace" colors in the ./vscode/settings.json file and instead globally on the machine (i.e. "personal settings" vs project/team-shared settings

There is an open issue on this here #7 . I recommend upvoting the VS Code product issue related to this (see issue #7 for the link)
