### ISSUE TITLE
EMFILE: too many open files, scandir '~/JokesApp/ios/JokesAppTests'

### ISSUE THREAD

**Issue by deadcoder0904** [johnpapa/vscode-peacock#285]
**Versions (please complete the following information):**

- OS: Mac 10.14.6
- VS Code version: 1.38.1
- Peacock Version: 3.1.5

**Describe the bug**
The selection of Peacock's Favorite Color is slow. I can see the unnecessary lag. It's too much lag like 2-5s.

And I get tons of notifications saying `EMFILE: too many open files, scandir '~/JokesApp/ios/JokesAppTests'` & then the lag starts happening.

**To Reproduce**

1. Start a React Native project using `react-native-cli`
2. Open in VSCode
3. Start selecting favorite color in Peacock.
4. It should lag while getting too many notifications of `YourAppTests` folder inside `YourApp/ios/`.

**Expected behavior**
It should not lag.

**Comment by johnpapa** [comment]
Hi - i've done some testing and cannot repro. I "think" this may be due to some other extension.

If you can provide more details I will re-open this

thanks!

**Comment by deadcoder0904** [comment]
I am not starting React Native project soon & haven’t worked on too many apps at a time so I haven’t used Peacock in a while but I’ll open it if I see it again.

PS: Love Peacock & your new extension Cloak 👌

You make the best VSCode extensions out there 💖

**Comment by johnpapa** [comment]
thank you!
