### ISSUE TITLE
Introduce "Surprise Me on Every Startup" feature

### ISSUE THREAD

**Issue by MV88** [johnpapa/vscode-peacock#288]
**Is your feature request related to a problem? Please describe.**
No it's not a problem

**Describe the solution you'd like**
I would like to have applied a random color on every startup.
I know it can be the opposite purpose of this extension, but if you are using vscode for only one project it can be nice to have color changing every time.
This is for sure a low priority issue

**Describe alternatives you've considered**
the actual workaround is to remove color, close and reopen vs code, then i have a new random color

**Additional context**
I think the lines involved are [these](https://github.com/johnpapa/vscode-peacock/blob/22f02e2831d627e1195dab8479cf37502428c0c0/src/extension.ts#L87-L89) ones and there is a need to add a new flag for this feature.

I'm new to typeScript, but i can try to provide a PR if you accept, if not sorry for the noise

**Comment by johnpapa** [comment]
I appreciate the idea but I am also trying to limit hte API surface area as the code is getting more and more complex. Since this can be done by choosing a new random color , I think we'll mark this closed as there is a workaround.

Thanks
