### ISSUE TITLE
Don't write settings if they already exist

### ISSUE THREAD

**Issue by orokanasaru** [johnpapa/vscode-peacock#289]
**Is your feature request related to a problem? Please describe.**
When I change a settings file (*.code-workspace.json / settings.json), I keep it sorted. Whenever I reopen the workspace / folder, peacock changes the order of settings in colorCustomizations, even though none of the colors are actually being changed.

**Describe the solution you'd like**
Ideally, peacock would respect the existing order. Barring that, it would only write if there were actually changes, and writing sorted keys in that case would be preferable.

**Describe alternatives you've considered**
Nothing really.

**Additional context**
![image](https://user-images.githubusercontent.com/5751627/66708772-e04b5500-ed0a-11e9-8ffe-74588e95a783.png)

**Comment by johnpapa** [comment]
Thanks. I'm very open to PRs

**Comment by johnpapa** [comment]
Here is the code from the file `apply-color.ts` in the function `export async function applyColor(input: string) {`

```typescript
  // Delete all Peacock color customizations from the object
  // and return pre-existing color customizations (not Peacock settings)
  const colorCustomizationsWithoutPeacock = deletePeacocksColorCustomizations();

  // Get new Peacock colors.
  const newColors = prepareColors(color);

  // merge the existing colors with the new ones
  // order is important here, so our new colors overwrite the old ones
  const colorCustomizations: any = {
    ...colorCustomizationsWithoutPeacock,
    ...newColors,
  };

  await updateWorkspaceConfiguration(colorCustomizations);
```

This is why the order is changed. For the order to remain the same, each setting and color would have to examined and then added/replaced, if needed.

If someone wants to stab at a PR with some tests, this could be a good contribution.

**Comment by johnpapa** [comment]
this will be in 3.6.1 

however - it does not work in some cases due to vs code api and how it caches

https://github.com/microsoft/vscode/issues/92733
