### ISSUE TITLE
consider other colorizations

### ISSUE THREAD

**Issue by johnpapa** [johnpapa/vscode-peacock#3]
activity bar?
status bar?
none

**Comment by tehshane** [comment]
+1 for an activity bar option

**Comment by ctrlShiftBryan** [comment]
+ 1 to activity bar or other. I usually run in full screen mode in OSX so I have no visible titlebar

**Comment by lmuller18** [comment]
+1 to activity bar and status bar and even highlight color. Right now I have a couple of gists for different themes that I just pull down into new projects to change the colors but being able to quickly achieve the same thing through this extension would be a much better workflow.

**Comment by johnpapa** [comment]
In v.0.0.7  ...

You can tell peacock which parts of VS Code will be affected by when you select a color. You can do this by setting the property `peacock.affectedSettings` to one or more of the valid values below.

```javascript
// Valid settings you can choose to be affected
"peacock.affectedSettings": [
    "activityBar",
    "statusBar",
    "titleBar"
  ]
```
