### ISSUE TITLE
Use new customization properties available in October 2019 (v1.40)

### ISSUE THREAD

**Issue by mimatn** [johnpapa/vscode-peacock#304]
**Is your feature request related to a problem? Please describe.**
VSCode October 2019 (version 1.40) introduced various new colour customizations, some of which are very helpful and enhance usability:  activityBar.activeBorder, activityBar.activeBackground, window.activeBorder and window.inactiveBorder.

**Describe the solution you'd like**
Peacock-generated theme should calculate some colour tones for these properties, to fully enable the usability advantages that they provide.

**Describe alternatives you've considered**
Right now, peacock works really well. This issue is just a reminder to take advantage of a new feature.

**Additional context**
Release notes links:
[Activity Bar Indicator](https://code.visualstudio.com/updates/v1_40#_activity-bar-indicator)
[Themable window border](https://code.visualstudio.com/updates/v1_40#_themable-window-border)

Thank you for this excellent extension!

**Comment by musicfuel** [comment]
I came here to offer this same suggestion and I see that @mimatn already beat me to it 😄

**Comment by jabacchetta** [comment]
Happy to see the window border setting, which is awesome for those of us who work in full screen mode with both the activity bar and status bar hidden. Looking forward to seeing this in Peacock!

**Comment by johnpapa** [comment]
`activityBar.activeBorder` is already in place in v3.2.0. I enabled it as part of the activity bar checkbox, because I prefer to avoid increasing the settings surface area, if possible.

I tired the others and couldn;t decide if these would be desired. If so, we may need more settings. Let's have a discussion here first about each.

```
activityBar.activeBackground
window.activeBorder
window.inactiveBorder
```

**Comment by johnpapa** [comment]
i'm going to close this. but if anyone wants any of the settings for windows, please open an issue and state your case. i'm all ears :)
