### ISSUE TITLE
Unexpected mixed colors when user reconfigure their settings

### ISSUE THREAD

**Issue by souzara** [johnpapa/vscode-peacock#31]
To reproduce:
 - Configure "peacock.affectedElements" with the three options (titleBar, activityBar, statusBar)
 - Execute command "Peacock: Color to Random"
 - Configure "peacock.affectedElements" with the two options (titleBar, activityBar)
 - Execute command "Peacock: Color to Random"
As you can see, status bar is not with default color.

**Comment by johnpapa** [comment]
merged. thanks!

**Comment by johnpapa** [comment]
now in 0.2.1
