### ISSUE TITLE
Adopt the new 'extensionKind' format

### ISSUE THREAD

**Issue by egamma** [johnpapa/vscode-peacock#313]
As of VS Code 1.40 the `extensionKind` attribute in the `package.json` of the extension can be an array, pls see the [documentation](https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location). 

We will be deprecating the `string` type for `extensionKind` property in favour of `string array` type.

The `extensionKind` attribute should be set to `["ui", "workspace"]`. Indicating that the extension can run both as a UI extension and as a workspace extension (e.g. in the browser).

**Comment by johnpapa** [comment]
Thank you @egamma for creating this issue!

Have a Happy Holiday season!

**Comment by johnpapa** [comment]
closed by #314

**Comment by johnpapa** [comment]
@egamma Thanks for the PR! I merged it tonight.

Would this cause any errors if left as a string in the package?
