### ISSUE TITLE
Peacock stopped working with latest VSCode 1.40.2

### ISSUE THREAD

**Issue by gmclelland** [johnpapa/vscode-peacock#315]
**Versions (please complete the following information):**

- OS: [tested on mac and windows]
- VS Code version [1.40.2 and 1.41.0-insider]
- Peacock Version [3.2.0]

**Describe the bug**
Apologies if this has already been reported elsewhere, but I noticed Peacock stopped working after upgrading to the latest VSCode.

Any ideas as to what could be causing if from loading?  I also noticed the only VSCode command available is to open Peacock documentation which seems weird.

Thanks for making this extension, it's very helpful.

**Comment by johnpapa** [comment]
Thank you @gmclelland for creating this issue!

Have a Happy Holiday season!

**Comment by johnpapa** [comment]
Hello - thanks for reporting this ... can you share what is not working please?

I am using 1.41.0 insider and it works. If you can clarify, I would be happy to research it.

**Comment by gmclelland** [comment]
I noticed when my VSCode(1.40.2 on Mac) updated to the latest version that Peacock stopped working.  The top(title bar) and bottom(status bar) of VSCode stopped showing my colors.  I thought that was strange so I tried to install Peacock on my VSCode Insiders(1.41.0 on Mac) and noticed it wasn't doing anything either.

So then I tried installing a fresh install of VSCode on my Windows machine with Peacock and nothing happened either.  During this time I tried setting the option for: 
![Peacock Options](https://user-images.githubusercontent.com/40570/69931070-87d34100-148b-11ea-8e71-b8bcaddbfdc7.jpg)

I then restarted VSCode and created some new VSCode windows, but nothing changed visually.  I also tried Cmd+Shift+P and started typing "Peacock", but the only suggestion shown was "open Peacock documentation" which seems weird, seems like their should be others displayed?

FYI..Peacock is the only extension installed on my VSCode - Insiders(on Mac) and VSCode (on Windows).

Let me know if their is anything else I can provide to help.

**Comment by johnpapa** [comment]
Thanks for the details.

> the only suggestion shown was "open Peacock documentation" which seems weird, seems like their should be others displayed?

This is in the FAQ. It is because Peacock cannot do its job unless a workspace is open. It's a VS Code limitation.

Is this what is causing all of the issues?

**Comment by gmclelland** [comment]
Dang, I knew I was missing the obvious.  I forgot that Peacock only works on Workspaces and not VSCode Windows.  Sorry to bother.

**Comment by johnpapa** [comment]
no worries at all.

you gave me an idea to solve this common confusion. i'll open an issue to discuss ... but the idea I have is to put an item in the menu that says something like "Peacock is disable when not in a workspace"

The key is making it short and actionable. Not sure - but its an idea

**Comment by gmclelland** [comment]
> but the idea I have is to put an item in the menu that says something like "Peacock is disable when not in a workspace"

Sounds like a good suggestion.

The only other thing I would suggest is to add a step in the documentation's README.md:

```
Quick Usage
Let's see Peacock in action!

1. **Create/Open a VSCode Workspace** (Peacock only functions in Workspaces)
2. Press F1 to open the command palette
3. Type Peacock
4. Choose Peacock: Change to a favorite color
5. Choose one of the pre-defined colors and see how it changes your editor

Now enjoy exploring the rest of the features explained in the docs!
```

That part of the README.md is the first thing I checked when things weren't working for me.  I added line 1 in the steps above.

**Comment by johnpapa** [comment]
thanks. I added this to the docs guide and readme

**Comment by gmclelland** [comment]
Thank you.

I just checked the README.md.  It looks like a phrase "Peacock only works in Workspaces) was linked with http://localhost:8080/guide/#peacock-commands-are-not-appearing.

That link doesn't look correct to me?

**Comment by johnpapa** [comment]
thanks, just fixed - should deploy soon
