### ISSUE TITLE
[Feature Request] Add option to change inactive titlebar color as well

### ISSUE THREAD

**Issue by Stanzilla** [johnpapa/vscode-peacock#321]
**Is your feature request related to a problem? Please describe.**
Requesting a new option

**Describe the solution you'd like**
A setting to also change the color of `titleBar.inactiveBackground`

**Describe alternatives you've considered**
N/A

**Additional context**

Should probably use a different darken() than foreground but the same color.

**Comment by johnpapa** [comment]
Thank you @Stanzilla for creating this issue!

Have a Happy Holiday season!

**Comment by johnpapa** [comment]
thanks for the request. I don't think i'll work on this one. it will affect a lot of code, and I want to be careful not to have regression issues. thanks tho
