### ISSUE TITLE
Subtle color changes aren't subtle at all

### ISSUE THREAD

**Issue by oliversalzburg** [johnpapa/vscode-peacock#324]
**Versions (please complete the following information):**

- OS: Windows 10
- VS Code version 1.41
- Peacock Version 3.20

**Describe the bug**
The extension description says the color of the UI is _subtly_ changed, but the colors that are applied by default are everything but subtle.

**To Reproduce**

1. Press <kbd>F1</kbd>.
2. Go to `Peacock: Change to a Favorite Color`
3. Inspect the UI

**Expected behavior**
The existing color of the UI is subtly adjusted towards a given tint.

I'm only making a note of this because the subtlety was explicitily mentioned as a feature of this extension and I found the choice of default colors to be very unpleasant visually. I use a dark theme and the colored borders have an immense contrast that is further highlighted by the Remote View button. It didn't feel intentional, even though the screenshots of the extension seem to suggest it is.

**Comment by johnpapa** [comment]
Thank you @oliversalzburg for creating this issue!

Have a Happy Holiday season!

**Comment by johnpapa** [comment]
thanks. what is your suggestion?

**Comment by oliversalzburg** [comment]
@johnpapa I was mostly wondering if that was even by-design or not. I later found the option to lighten and darken the colors, which seemed to result in more subtle color changes and which seemed like it would be more appropriate to fit the goal of subtle color changes.

So I figured that the intention was that the extension picks a base color and then applies sublte lightness changes to each workspace or something along those lines. I was probably just expecting the wrong effect.

**Comment by johnpapa** [comment]
ok

no worries.
