### ISSUE TITLE
Reduce notifications when installing extension

### ISSUE THREAD

**Issue by bpasero** [johnpapa/vscode-peacock#332]
Referring to: 

![image](https://user-images.githubusercontent.com/900690/71516872-b20df800-28ab-11ea-87e1-54371bc5dd28.png)

Which I got after installing LiveShare. We would like to make extensions aware that notifications should only be used if absolutely necessary. Not sure that is the case here?

I personally read the notification and had no clue what it meant. Suggest to remove it.

**Comment by johnpapa** [comment]
Thank you @bpasero for creating this issue!

Have a Happy Holiday season!

**Comment by johnpapa** [comment]
Are you saying you had peacock already and then installed live share, and then this appeared?

**Comment by bpasero** [comment]
@johnpapa no, I had a fresh Code installation and installed LiveShare as first extension. This seems to bring in Peacock extension as well which brings up that said notification.

**Comment by johnpapa** [comment]
ok. there is a live share extension pack which includes peacock. 

I think I agree with you - that the initial notification is not necessary. the intent had been to let people know that it was doing something to their settings, but I dont think that's a necessary thing to do.

I'll open a PR to remove this.

thanks

**Comment by johnpapa** [comment]
this will be in v3.3.0
