### ISSUE TITLE
Add support for open colors

### ISSUE THREAD

**Issue by lipis** [johnpapa/vscode-peacock#335]
Would be nice to be able to chose a color from this open source pallet.

https://yeun.github.io/open-color/

**Comment by johnpapa** [comment]
Thank you @lipis for creating this issue!

Have a Happy Holiday season!

**Comment by johnpapa** [comment]
they are very nice and you can enter those manually. at this time I wont be adding a large set of colors to a pick list, as to keep the pre-canned choices limited.

thanks tho!
