### ISSUE TITLE
Titlebar setting does not work

### ISSUE THREAD

**Issue by iaarnio** [johnpapa/vscode-peacock#34]
Strangely the 'titleBar' does not change colors for me. All other color options ('statusBar' and 'activityBar') work just OK.  Vscode restarted (even MacOS restarted) after extension installation. Also settings.json saved for sure (can see changes when enabling 'statusBar' and 'activityBar')

setting.json: 
  "peacock.affectedElements": [
    "titleBar",
    "statusBar",
  ],

But only statusBar will change color with e.g. 'Peacock: color to random'.
The titlebar will stay in MacOS default color.

I tried disabling all other extersions (except Peacock) and reloading Vscode.
I tried with macOS dark and light modes. 

MacOS Mojave 10.14.3
VSCode 1.31.1

**Comment by johnpapa** [comment]
might be a silly question - are you in full screen? titlebar is hidden then.

**Comment by deadcoder0904** [comment]
works for me fine. i think u must be in full screen as @johnpapa said :)

**Comment by iaarnio** [comment]
No silly questions but I use Vscode in windowed (i.e non fullscreen mode).  

Initially:
![image](https://user-images.githubusercontent.com/8036867/53472978-dd4c6e80-3a71-11e9-97ac-4dfc31558df1.png)

Changing to random color:
![image](https://user-images.githubusercontent.com/8036867/53473018-fe14c400-3a71-11e9-9df1-44ff8da07665.png)

Result:
![image](https://user-images.githubusercontent.com/8036867/53473036-07059580-3a72-11e9-8226-6908883cb782.png)

**Comment by johnpapa** [comment]
my laptop is sierra still, so i dont know if mojave has something to do with this (dark mode on it)

can someone else try it on mojave?

**Comment by deadcoder0904** [comment]
@johnpapa I'm on Mac OS Mojave v10.14.2 using Dark Mode. Works fine for me :)

**Comment by BrsJsk** [comment]
Mac OS Mojave v10.14.3..does't work for me

**Comment by iaarnio** [comment]
I'm also on v10.14.3. I've tried to stop all possible 3rd party software too. Even booting to safe mode. 
Still same results.

**Comment by johnpapa** [comment]
Something to check ... Peacock relies on there being a workspace which means there can be a `.vscode/settings.json` folder and file. Peacock will create that file (and folder) as long as you have a project/folder open. Do you have a project or folder open?

**Comment by akaspi** [comment]
Overriding Peacock settings to:
`"peacock.affectStatusBar": true, "peacock.affectActivityBar": true` and **THEN** chaging the color using Peacock command solves it for me.

Mac OS Mojave v10.14.3

**Comment by johnpapa** [comment]
@iaarnio is this resolved for you? 

I cannot reproduce - but want to help if we can figure this out

**Comment by iaarnio** [comment]
I do have .vscode/settings.json on my work directory:
```
cat .vscode/settings.json
{
    "search.exclude": {
        "**/dist": true
    },
    "workbench.colorCustomizations": {
        "titleBar.activeBackground": "#30cf6b",
        "titleBar.activeForeground": "#e7e7e7",
        "titleBar.inactiveBackground": "#30cf6b",
        "titleBar.inactiveForeground": "#e7e7e7",
        "statusBar.background": "#30cf6b",
        "statusBar.foreground": "#e7e7e7"
    }
}
```

**Comment by iaarnio** [comment]
@akaspi statusBar and activityBar also work for me. Could you verify if you can also change **titleBar**?

Also noticed with new Peacock 0.5.0 non-json settings that when I set e.g.:
![vscode](https://user-images.githubusercontent.com/8036867/53720754-2cc3dd80-3e6a-11e9-8220-ccffd199a6f4.jpg)
Then my settings.json still shows only:
![statusbar](https://user-images.githubusercontent.com/8036867/53720826-57ae3180-3e6a-11e9-8392-387d420dc37b.jpg)

However, adding manually also ´´´"peacock.affectTitleBar": true,´´´ does not still affect titleBar color.

**Comment by musicfuel** [comment]
@iaarnio Are you sure that you have your VS Code settings for the titleBar configured to custom? If it is set to native on the Mac I get the exact behavior you are describing because the native OS is controlling the titleBar.

<img width="1096" alt="screen shot 2019-03-04 at 9 56 32 pm" src="https://user-images.githubusercontent.com/1085791/53780181-c7eba000-3ec8-11e9-9583-3f973ef8c4db.png">

When I have it set to custom then I am able to use Peacock to set the titleBar as expected.

<img width="911" alt="screen shot 2019-03-04 at 10 00 28 pm" src="https://user-images.githubusercontent.com/1085791/53780216-f8cbd500-3ec8-11e9-98b4-12822641764b.png">

**Comment by iaarnio** [comment]
@musicfuel  I checked this but the default custom title bar style was in use:

![image](https://user-images.githubusercontent.com/8036867/53792877-56960680-3f35-11e9-9a73-c503cc757aaa.png)

I tried also switching it to native & restarting and back to custom & restarting. 
Still the VSCode titlebar refuses to change color.

**Comment by musicfuel** [comment]
Here is the code that is making the determination of when to use native or custom: https://github.com/Microsoft/vscode/blob/d4150608c06f76e3d4c8c81a5bf434869be5072e/src/vs/platform/windows/common/windows.ts#L260

Based on the code, the title bar will be forced into native mode regardless of the setting if:

* You are running a build that you built from source code
* You are running as the Extension Development Host (doesn't look like it from your screenshots)
* You have the `window.nativeTabs` setting set to **true**
* You have the `window.nativeFullScreen` setting set to **false**

Are any of those relevant to you?

**Comment by emreSerbetcioglu** [comment]
I had the `window.nativeTabs` set to **true**, when I set it to **false**, the issue is resolved.

**Comment by iaarnio** [comment]
Thanks @musicfuel !  

Setting the nativeTabs & nativeFullScreen like you instructed solved this for me too.

**Comment by johnpapa** [comment]
This is awesome digging! Thank you

Would one of you want to make a PR to the Readme to add a section at the bottom for FAQs that explains this? When we figure it issues, it's great to share in case someone else runs into it.

**Comment by musicfuel** [comment]
I can formalize my comment above into a note in the README. A PR is forthcoming.
