### ISSUE TITLE
[Minor bug] activityBar.activeBackground not sync with it background

### ISSUE THREAD

**Issue by CuongNgMan** [johnpapa/vscode-peacock#345]
**Versions (please complete the following information):**

- OS: Windows 10
- VS Code version: latest
- Peacock Version: 3.3.1

**Describe the bug**
- There is a minor issue when I used Peacock with Shades of Purple theme
- As in the screen below, you can see that the active item color does not sync with activity bar's background

**To Reproduce**

1. Install Peacock
2. Install Shades of Purple theme and use it as default theme
3. Active Peacock

**Expected behavior**
- The active item should have the same color as Activity Bar background

**Screenshots**
![active item not sync](https://user-images.githubusercontent.com/29836185/73456224-1a1c9600-43a4-11ea-882d-615396f29be3.png)

**Additional context**
- After several try, I found that these below settings are useful for this issue

- activityBar.activeBackground
- activityBar.activeBorder
- activityBar.activeFocusBorder

**Comment by johnpapa** [comment]
Thank you @CuongNgMan for creating this issue!

**Comment by johnpapa** [comment]
thanks.

have you tried this with other themes? are you sure it is just with that specific theme?

**Comment by CuongNgMan** [comment]
I only see this issue with that specific theme as of now.
But still, it would be better to make the color of activeBackground in sync with Activity Bar.

**Comment by MadeByMike** [comment]
I get this with all themes :(

**Comment by johnpapa** [comment]
Thanks for the details.

I think I see what is happening. Peacock does not set the `activityBar.activeBackground`. So if your theme uses that color, it could look odd. This would only be noticeable if the theme you use colors that setting, which is why I was not seeing it (and had not been reported before)

I think the appropriate fix would be to set the `activityBar.activeBackground` to the same color as Peacock sets the `activityBar.background`.

**Comment by johnpapa** [comment]
fix is now in 3.6.0

Notice the following image. The toolbar on the left is what peacock used to look like if a thee colored the activitybar activebackground. The image on the right shows what this fix does.

![image](https://user-images.githubusercontent.com/1202528/76255643-eb0c0680-6224-11ea-8bc2-f81215b5ad24.png)
