### ISSUE TITLE
Be able to use Peacock without using a workspace

### ISSUE THREAD

**Issue by devpato** [johnpapa/vscode-peacock#357]
**Is your feature request related to a problem? Please describe.**
Peacock currently works with workspaces

**Describe the solution you'd like**
The same way you select a theme like using the extension, theme selected remains like that every time I open VS Code.

**Comment by johnpapa** [comment]
Thank you @devpato for creating this issue!

**Comment by johnpapa** [comment]
closing as s duplicate of #7 

Love to hear any new thoughts in that issue
