### ISSUE TITLE
Editor colours aren't reverted when uninstalling

### ISSUE THREAD

**Issue by c24w** [johnpapa/vscode-peacock#36]
I just applied a random colour to my editor, then uninstalled Peacock, but my editor has remained a fabulous shade of fuschia:

<img src="https://user-images.githubusercontent.com/710406/53405687-453a8080-39b0-11e9-9e41-9d3d40dff820.png" width="50%">

I tried reinstalling and calling Peacock's reset method, but that didn't work.  Also, VS Code immediately restores the `titleBar.*` settings when deleted from my user settings, so I thought this was just my life now.  Turns out I had to delete them from my workspace settings, then from my user settings.

**Comment by johnpapa** [comment]
Peacock sets you workspace's vscode settings file. You can either remove those settings in one of ways:

1. use the `Peacock - reset colors` menu option
2. manually remove them

Peacock does not set any colors in the user settings json. It does support some settings in the user settings, but they are ignored by vscode, and only used by peacock.

This works as designed
