### ISSUE TITLE
Only update settings when the user explicitly selects a favorite color

### ISSUE THREAD

**Issue by IEvangelist** [johnpapa/vscode-peacock#360]
**The problem**

While I fully understand that this extension is intended for workspace specific usage, I have set my colors in the user settings (globally). [User settings](https://code.visualstudio.com/docs/getstarted/settings#_settings-file-locations) are stored in the following locations (outside the workspace):

* Windows `%APPDATA%\Code\User\settings.json`
* macOS `$HOME/Library/Application Support/Code/User/settings.json`
* Linux `$HOME/.config/Code/User/settings.json`

Every time I open a new instance of Visual Studio Code, my local (workspace) *settings.json* file is overwritten by my user (global) settings. Often, I collaborate on projects that source control the *settings.json* file. This is very frustrating, as I always have to manually discard these changes.

![image](https://user-images.githubusercontent.com/7679720/75689149-5292e680-5c66-11ea-8e32-261194670ac7.png)

Ideally, I could use this extension to colorize my IDE with only needing to set my user settings. Then I could set my workspace *settings.json* later, individually when I need to.

**The solution**

The solution is rather simple. I would love for this extension to only write to the workspace *settings.json* file when the user explicitly selects a new favorite color. This would prevent the need to manually discard implicit changes that occur when opening the IDE with user settings, and the extension overwrites the workspace settings.

**Describe alternatives you've considered**

An alternative, but more complex option would be to calculate deltas on global settings, and let them override workspace settings -- taking on an aggregate color scheme for example. In this scenario, if the user has some colors from the user settings that are different than the colors in the workspace, take all colors from the user and remaining colors from the workspace - use that as the theme.

**Additional context**

Here is a list of related issues, as they exist today. It appears as though there is a misconception around the intent of this extension. Again, I understand it was initially designed for workspace only - but since Visual Studio Code lets developers specify user settings, those should be accounted for.

* [Peacock without a workspace: Allow option for colors to only affect one user and one instance](https://github.com/johnpapa/vscode-peacock/issues/7)
* [Don't write settings if they already exist](https://github.com/johnpapa/vscode-peacock/issues/289)
* [Make it more obvious that peacock can only work in a workspace](https://github.com/johnpapa/vscode-peacock/issues/333)
* [**Feature Request** Workspace Color Customization Overrides](https://github.com/johnpapa/vscode-peacock/issues/343)
* [Don't reset the color scheme every time Code opens](https://github.com/johnpapa/vscode-peacock/issues/355)

**Comment by johnpapa** [comment]
Thank you @IEvangelist for creating this issue!

**Comment by johnpapa** [comment]
I'm a little confused on which file you don't want written to and what you don;t want written to it, and if so, what you do want? Can you give an example?

Currently Peacock doesnt write anything to workspace settings until you select a color for your workspace. Peacock does write to user settings, though some of that has been removed in the latest version (3.5.0) as it no longer writes the default favorites til you change them.

**Comment by IEvangelist** [comment]
Sure, let me try to explain it a little better.

Every time I open **Visual Studio Code**, the Peacock extension writes to my workspace `.vscode/settings.json` file for the workspace I'm working in. I can only assume that it somehow reads my global (user) settings, which are located here `%APPDATA%\Code\User\settings.json`. It reads these, and then it writes those same settings here `.vscode/settings.json`.

> Currently Peacock doesnt write anything to workspace settings until you select a color for your workspace.

This issue might be a symptom of how **Visual Studio Code** handles the precedence of settings, workspace vs. global (user). I'm currently using the latest version of Peacock, 4.5. If I find time, I'll create a pull request to fix this issue.

**Comment by johnpapa** [comment]
Are you storing all of your colors in user settings? is that why you do not want them in workspace?

```
activityBar.background = #d04649
  activityBar.activeBorder = #37cb34
  activityBar.foreground = #e7e7e7
  activityBar.inactiveForeground = #e7e7e799
  activityBarBadge.background = #37cb34
  activityBarBadge.foreground = #15202b
  titleBar.activeBackground = #b52e31
  titleBar.inactiveBackground = #b52e3199
  titleBar.activeForeground = #e7e7e7
  titleBar.inactiveForeground = #e7e7e799
  statusBar.background = #b52e31
  statusBarItem.hoverBackground = #d04649
  statusBar.foreground = #e7e7e7

peacock: Peacock is now using #b52e31
```

**Comment by IEvangelist** [comment]
Yes, I’m storing them all in user settings and not in the workspace. And every time I’d open VSCode it would overwrite my workspace settings.

**Comment by johnpapa** [comment]
Thanks. 

I feel this is out of scope for peacock and not something I’ll be adding to it. 

Managing settings (various types exist - default - user - workspace )  is quite complicated. The code reflects this now. Having this new behavior would fundamentally change how parts of peacock work and user expectations. 

I recommend that if you want user settings that you grab the colors form peacock that you want, save those in settings, then remove peacock.
