### ISSUE TITLE
Cannot install on Mac Visual Studio Code

### ISSUE THREAD

**Issue by TheMFB** [johnpapa/vscode-peacock#363]
**Versions:**

- OS: Mac
- VS Code version: Version 1.27.2 (1.27.2)
- Peacock Version: 3.5.0

**Bug Description**
I've tried to install Peacock on the latest versions of VS Code for the past couple of weeks, with no results. Installing it from within VSCode, I get a "Failed to install 'johnpapa.vscode-peacock'." Trying to install it manually I get "Unable to install because, the depending extension 'johnpapa.vscode-peacock' compatible with current version '1.27.2' of VS Code is not found."

VSCode has no updates available to download, and I have it selected to auto-update. Any ideas?

Is there any additional information that would be helpful?

**Comment by johnpapa** [comment]
Thank you @TheMFB for creating this issue!

**Comment by johnpapa** [comment]
It looks like you have an old version of Code. Can you try updating it and then try again with Peacock?

**Comment by TheMFB** [comment]
Yup. Mac Catalina doesn't like updating this app apparently. I had to redownload, and then authorize to install an unsigned app. Thank you!
