### ISSUE TITLE
Better color chooser

### ISSUE THREAD

**Issue by LucaGabi** [johnpapa/vscode-peacock#364]
**Is your feature request related to a problem? Please describe.**
A better color picker is needed. It's hard to enter hex values ...

**Describe the solution you'd like**
A list of predefined colors would be good for start. A color picker would be perfect.

**Describe alternatives you've considered**
At least keep history of entered colors and display as colors not as text hex.

**Additional context**
-

**Comment by johnpapa** [comment]
Thank you @LucaGabi for creating this issue!

**Comment by johnpapa** [comment]
id love this feature. unfortunately there is not color picker for vs code yet. if an api opens for this, i'm interested.


thanks
