### ISSUE TITLE
Live Share integration seems to not work

### ISSUE THREAD

**Issue by cyberbiont** [johnpapa/vscode-peacock#367]
**Versions (please complete the following information):**

- OS: Windows 10 Pro x64
- VS Code version 1.43.0
- Peacock Version 3.6.0

**Describe the bug**
`Peacock: Change Live Share Color (Host)` or `Peacock: Change Live Share Color (Guest)` commands do not appear in command palette; 
When starting Live Share session color does not change.

**To Reproduce**

1. With LiveShare extension and Peacock installed, search for `Peacock: Change Live Share Color (Host)` or `Peacock: Change Live Share Color (Guest)` commands.  they doesn't show up.
It seems that second condition on which they are shown, peacock:liveshare == true (as specified in package.json contrubutes.menus.commandPalette) evaluates to false, after manually removing it those commands show up.
2. Manually set `peacock.vslsShareColor` in extension options.
3. Start Live Share session.
4. Color doesn't change.

**Expected behavior**
When starting Live Share session color should change to color specified in `peacock.vslsShareColor` setting.

**Comment by johnpapa** [comment]
Thank you @cyberbiont for creating this issue!

**Comment by johnpapa** [comment]
Perhaps @legomushroom or @lostintangent can take a look. I can’t run those tests for some reason.

**Comment by cyberbiont** [comment]
Strange, it seems like everything started to work. I will close the issue.

**Comment by JanSellner** [comment]
I think this issue still exists. I have the exact same problem with Peacock 3.7.0. on

> Version: 1.44.2
> Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
> Date: 2020-04-16T16:36:23.138Z
> Electron: 7.1.11
> Chrome: 78.0.3904.130
> Node.js: 12.8.1
> V8: 7.8.279.23-electron.0
> OS: Windows_NT x64 10.0.18363

Neither do the commands show up nor are the settings (e.g. "peacock.vslsJoinColor": "#832561") respected. The color won't change when starting a Live Share session.

**Comment by johnpapa** [comment]
@lostintangent or @legomushroom can you take a look please?

**Comment by legomushroom** [comment]
Will take a look today.

**Comment by legomushroom** [comment]
@legomushroom started [Live Share session](https://prod.liveshare.vsengsaas.visualstudio.com/join?2314CFCA0EE8C14BD85B1BEE5F281F0C983D) [![Live Share session](https://togezr-vsls-session-badge.azurewebsites.net/api/vsls-compact-badge?sessionId=2314CFCA0EE8C14BD85B1BEE5F281F0C983D&v=1588653071806)](https://prod.liveshare.vsengsaas.visualstudio.com/join?2314CFCA0EE8C14BD85B1BEE5F281F0C983D)

**Comment by legomushroom** [comment]
Cannot repro, need more details for the issue.
