### ISSUE TITLE
Not able to get Peacock working

### ISSUE THREAD

**Issue by gitmayoor** [johnpapa/vscode-peacock#374]
**Versions (please complete the following information):**

Version: 1.43.2 (user setup)
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

- Peacock Version 3.6.0

**Describe the bug**
- Installed extension
- Created Workspace and saved
- From command pallet, only seeing documentation, no other commands
- if I go to settings and under 'Workspace', if I type 'peacock', I see 19 items for it.

**To Reproduce**

Default installation and steps specified on doc not working.

**Expected behavior**
Expected to choose 'Peacock: Change to a favourite colour' option through command pallet.

**Additional context**

Is this due to VS code having 'workspace' settings under 'workspace.json' file. I don't see settings.json file under .vscode anymore. 

I'm sorry to open this under bug, I couldn't find any FAQ to answer this.

**Comment by johnpapa** [comment]
Thank you @gitmayoor for creating this issue!

**Comment by madbox** [comment]
Same problem

Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:52:11.516Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.15.0-91-generic

Peacock 3.6.0

**Comment by johnpapa** [comment]
have you tried this? https://papapeacockstorage.z13.web.core.windows.net/guide/#peacock-commands-are-not-appearing

**Comment by johnpapa** [comment]
Re-raising this ... have you tried https://papapeacockstorage.z13.web.core.windows.net/guide/#peacock-commands-are-not-appearing ?

**Comment by gitmayoor** [comment]
Sorry, didn't get a chance to update earlier.

Peacock only works if a workspace is open in Visual Studio Code because it
needs the settings.json file to work. When it is not in a workspace, all
commands are hidden and disabled except for the "Peacock: Open
Documentation" command.

As I mentioned earlier, I'm in a workspace, I'm able to edit my workspace
settings file (peacock specifics). But, still I don't see any commands with
command pallet option.

Everytime I need to change a color, I need to go into workspace settings
and do it manually.

**Comment by johnpapa** [comment]
There is a line of code that disables all commands unless you are in a workspace. So for some reason VS Code may not think you are in a workspace. usually that means you have a folder open .... the presence of the `.vscode` might not be the only thing indicating that. Can you try closing Code, then opening the folder where your project is fresh?

**Comment by gitmayoor** [comment]
![image](https://user-images.githubusercontent.com/12108790/80763440-81192a80-8b0c-11ea-95ce-3af9c470dbed.png)

As you can see,

1. I'm in a workspace (note, colour was manually changed )
2. No folders opened
3. I pressed F1 -> Peacock shows only document option

![image](https://user-images.githubusercontent.com/12108790/80763617-ea00a280-8b0c-11ea-9958-55c918502f39.png)

Here is what I've in my settings (workspace settings.json file)

Hope this helps. Please let me know if there is any other info I can provide.

**Comment by gitmayoor** [comment]
![image](https://user-images.githubusercontent.com/12108790/80763742-35b34c00-8b0d-11ea-9a06-d4db9038e4bc.png)

The previous screenshots were taken from a Remote-SSH editor, I thought perhaps that can cause issues.

This one is a local workspace, freshly opened without any files/folders in it. 

===**workspaces > foo.code-workspace > {} settings >** ===

{
	"folders": [],
	"settings": {
		"peacock.color": "#8FBC8F\t",
		"peacock.favoriteColors": [
			{ "name": "Gatsby Purple", "value": "#639" },
			{ "name": "Auth0 Orange", "value": "#eb5424" },
			{ "name": "Azure Blue", "value": "#007fff" }
		  ],
		"workbench.colorCustomizations": {
			"activityBar.background": "#afcfaf",
			"activityBar.activeBackground": "#afcfaf",
			"activityBar.activeBorder": "#8787b7",
			"activityBar.foreground": "#15202b",
			"activityBar.inactiveForeground": "#15202b99",
			"activityBarBadge.background": "#8787b7",
			"activityBarBadge.foreground": "#15202b",
			"statusBar.background": "#8fbc8f",
			"statusBarItem.hoverBackground": "#6fa96f",
			"statusBar.foreground": "#15202b",
			"panel.border": "#afcfaf",
			"sideBar.border": "#afcfaf",
			"editorGroup.border": "#afcfaf",
			"statusBar.border": "#8fbc8f"
		},
		"peacock.surpriseMeFromFavoritesOnly": true,
		"peacock.surpriseMeOnStartup": true,
		"peacock.remoteColor": "#3CB371",
		"peacock.affectTitleBar": false,
		"peacock.affectAccentBorders": true
	},
	"peacock.elementAdjustments": {}
}

====

**Comment by johnpapa** [comment]
HI - I believe when you see the "add folder" on the left, that means VS Code doesnt think you are in a workspace.

The key thing here is that Peacock needs access to the `.vscode/settings.json`. So if this has changed, I could make a change to make this work.

 @egamma can you help confirm if I have this correctly?

**Comment by gitmayoor** [comment]
Hey, yes. You are correct!

![image](https://user-images.githubusercontent.com/12108790/80765677-980e4b80-8b11-11ea-89a9-c0ac225dbeda.png)

I just went ahead and added a folder to the workspace and after that I see all the options as documented. 

Should I close this off then?

**Comment by johnpapa** [comment]
I’m glad it works for you now. 

Yes. Let’s close this as this is how can Code works. 

Thanks for the collaboration

**Comment by gitmayoor** [comment]
Sounds good. Thank you.

Summary:
For VS Code to consider a workspace, a workspace should have a folder added. 

As this is not an issue with peacock, closing this issue as WAD.
