### ISSUE TITLE
[Feature] Set titlebar.border and statusBar.border along with title and border colors

### ISSUE THREAD

**Issue by ivnnv** [johnpapa/vscode-peacock#377]
**Versions:**
- OS: MacOS
- VS Code version 1.43.2
- Peacock Version 3.6.0

**Describe the bug**
`titlebar.border` and `statusBar.border` aren't being modified in any way when changing color scheme.

Im using "Github Plus" theme with some global modifications on my user's `settings.json.workbench.colorCustomizations`, and everything works beautifully when I change to any color scheme on any project, but realized this two elements remain the same, please note the pink lines up and down.

**Expected behavior**
These values should be computed to something matching color scheme.

**Screenshots**
![border1](https://user-images.githubusercontent.com/23552631/78569824-72e53080-7824-11ea-988f-2d41b183adba.png)

**Additional context**
Add any other context about the problem he
![border2](https://user-images.githubusercontent.com/23552631/78569832-75478a80-7824-11ea-8b70-32dc00c5b703.png)
![border3](https://user-images.githubusercontent.com/23552631/78569834-75e02100-7824-11ea-9431-142177266889.png)

**Comment by johnpapa** [comment]
Thank you @ivnnv for creating this issue!

**Comment by johnpapa** [comment]
from the screen shot it looks like you are changing the colors in the user settings. those will be overridden by the workspace settings (which is what peacock uses).

I'm not sure what steps you are following. can you type out the steps so I can reproduce the entire stream?

**Comment by ivnnv** [comment]
Hi,
There are indeed color customizations on my users global settings (`#FABADA`) pink borders for this example).

Then when configuring peacock on a project (pressing `F1` + `peacock` anywhere), its not creating any computed `titleBar.border` or `statusBar.border` on the project settings, so for those keys VSCode fallback to user's, and thats why they are still pink in the screenshots.

These are my color customizations on my user's settings:
```
"workbench.colorCustomizations": {
    "activityBar.background": "#33325f",
    "tab.activeForeground": "#202041",
    "tab.inactiveForeground": "#656581",
    "tab.activeBorder": "#2451e6",
    "editor.background": "#fefefd",
    "editor.lineHighlightBackground": "#f5f4f4",
    "editor.selectionBackground": "#dadada",
    "gitDecoration.modifiedResourceForeground": "#61503c",
    "gitDecoration.deletedResourceForeground": "#720101",
    "editorLineNumber.foreground": "#444444",
    "editor.findMatchBackground": "#fdffbb2c",
    "editor.selectionHighlightBackground": "#fbfdb8a8",
    "editor.findMatchHighlightBackground": "#fcffa2a8",
    "sideBar.foreground": "#16181b",
    "sideBarSectionHeader.background": "#b2bdce",
    "list.activeSelectionForeground": "#FFFFFF",
    "list.activeSelectionBackground": "#9db1ce",
    "list.inactiveSelectionForeground": "#30343a",
    "list.inactiveSelectionBackground": "#dbe5f3",
    "terminal.foreground" : "#F8F8F8",
    "terminal.background" : "#1f1f3b",
    "titleBar.activeBackground": "#3c4c80",
    "titleBar.activeForeground": "#FFFFFF",
    "titleBar.inactiveBackground": "#33325f",
    "titleBar.border": "#FABADA",
    "statusBar.border": "#FABADA",
    "statusBar.background": "#3c4c80",
    "statusBar.foreground": "#FFFFFF",
    "statusBar.debuggingForeground": "#FFFFFF",
    "statusBar.debuggingBackground": "#753462",
},
```
And these are the only keys generated on the workspace settings:
```
"workbench.colorCustomizations": {
  "activityBar.background": "#852b0e",
  "activityBar.activeBackground": "#852b0e",
  "activityBar.activeBorder": "#0f902f",
  "activityBar.foreground": "#e7e7e7",
  "activityBar.inactiveForeground": "#e7e7e799",
  "activityBarBadge.background": "#0f902f",
  "activityBarBadge.foreground": "#e7e7e7",
  "titleBar.activeBackground": "#571c09",
  "titleBar.inactiveBackground": "#571c0999",
  "titleBar.activeForeground": "#e7e7e7",
  "titleBar.inactiveForeground": "#e7e7e799",
  "statusBar.background": "#571c09",
  "statusBarItem.hoverBackground": "#852b0e",
  "statusBar.foreground": "#e7e7e7"
},
"peacock.color": "#571c09",
```

Missing:
`titleBar.status`
`statusBar.status`

Hope this clarifies all.

**Comment by johnpapa** [comment]
did you check the settings of peacock to see if titlebar and status are enabled?

**Comment by ivnnv** [comment]
Yes I checked it and they are both enabled:

Activating "Affect accent borders" only seems to affect inner borders (those contiguous between sidebar/debugConsole/editor) but not those on the title/status bars.

![config](https://user-images.githubusercontent.com/23552631/78610411-0f2f2780-7865-11ea-97c1-0e256eb052d6.png)

Can't you reproduce it adding
```
"workbench.colorCustomizations": {
    "titleBar.border": "#FABADA",
    "statusBar.border": "#FABADA",
}
```
to your user's config and then setting a color scheme to check if pink remains on those 1px top/bottom borders?

**Comment by johnpapa** [comment]
Yes, peacock still works for me even if I add those. But ... you just mentioned 

```
"workbench.colorCustomizations": {
    "titleBar.border": "#FABADA",
    "statusBar.border": "#FABADA",
}
```

Peacock doesnt change the title or status bar borders. It changes the backgrounds (and font colors) of the titlebar and statusbar.

Notice that you images above still have pink title and status bar borders

Can you clarify what you are not seeing ... maybe you didnt mean border?

**Comment by ivnnv** [comment]
> Peacock doesn't change the title or status bar borders. 

Thats the exact thing Im reporting:
![titleBar border](https://user-images.githubusercontent.com/23552631/78644584-627d9600-78b6-11ea-9e86-6cd99881f80a.png)
+
![statusBar border](https://user-images.githubusercontent.com/23552631/78644586-63aec300-78b6-11ea-8ff5-81550202ba5d.png)


Is this intentional for any  specific reason? I think it's doable and that it should (the same way than inner borders are changed).

I can even make the PR myself if you agree this be implemented.

Best.

**Comment by johnpapa** [comment]
I think I finally understand - you are asking to add a feature to set the titleBar and statusBar borders. I had thought you were reporting an error or problem, based on how this was written. I'll change the title to reflect your request.

I can see why you might want that, given the thee that you use has pink borders and you override your colors (I'm assuming since I see this in your settings files).

Some things to consider:
1. peacock is not a theme, it is intended to work with themes, only coloring specific places
1. peacock is intended to stay in its zones. title and status and activity are those zones
1. peacock should not expand its reach
1. peacock should limit its settings. enabling title should affect all title related colors

Given that, the titlebar and statusbar borders are interesting. they are  in the Peacock zones, but this has not been reported til now .... so it makes me wonder if most themes dont bother with borders. That is possible.

One option is to  include borders in the title and statusbar settings, and set to the same colors, respectively. Given that this hasnt been reported I want to reflect on this for a bit to make sure there are no adverse side effects.

**Comment by ivnnv** [comment]
Thanks for the complete review of the case John and for taking the time and giving interest on this issue/feature.

From my point of view and already thinking in the implementation and given your concerns, I think that adding this feature shouldn't cause any side effects as this would be my approach:

```
if (!PeackockSettings.affectTitleBar) {
  // nothing happens, just like now
} else {
  // PeackockSettings.affectTitleBar is On {
  if (!theme.colorCustomizations.?titleBar.?border ) {
    // customization doesnt exists on the theme: ignore
  }
  if (!userSettings.colorCustomizations.?titleBar.?border ) {
    // customization doesnt exists on the user settings: ignore
  }
  if (theme.colorCustomizations.?titleBar.?border || userSettings.colorCustomizations.?titleBar.?border) {
    // this is where we could take the actual applied color for titleBar.border
    // (userPref take preference over theme if both exists)
    // and apply coloring based on the selected peacock scheme
  }
}

[same for statusBar]
```

**Comment by johnpapa** [comment]
vs code's api handles that if/then logic for us. it's nice. adding border for these is quite simple in logic, if it is grouped with the rest of titlebar and statusbar (separately).

i'll think about this.

**Comment by ivnnv** [comment]
@johnpapa thanks for implementing this! 🙌
