### ISSUE TITLE
"Change to a favorite color" during folder opening does not do anything

### ISSUE THREAD

**Issue by tommck** [johnpapa/vscode-peacock#385]
**Versions (please complete the following information):**

Peacock: 3.7.0

About VS Code:

> Version: 1.44.2 (user setup)
> Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
> Date: 2020-04-16T16:36:23.138Z
> Electron: 7.1.11
> Chrome: 78.0.3904.130
> Node.js: 12.8.1
> V8: 7.8.279.23-electron.0
> OS: Windows_NT x64 10.0.17134
> 

**Describe the bug**
when loading a folder (either by running `code [folder]` or opening a folder from inside vs code) and immediately running "Ctrl-Shift-P" and choosing `Peacock: Change to a favorite color`, nothing happens.  No message, no list to choose.  The message is just ignored.

**To Reproduce**
See the bug description

**Expected behavior**
The command should do *something*, preferably pop up the color options as normal

**Comment by johnpapa** [comment]
Thank you @tommck for creating this issue!

**Comment by johnpapa** [comment]
Hi - I'm trying to understand how to reproduce this, but I can't seem to do so.

Could you share some screen shots of the steps?

**Comment by tommck** [comment]
I have a bunch of extensions installed, so startup of the extensions can take a bit of time.  All I do is open a project (usually relatively large as well) and then immediately do Ctrl-Shift-P and select "Peacock: Change to a favorite color" and hit enter (I'm a keyboard guy)

This same thing will work a minute later when everything is finished loading/initializing

**Comment by tommck** [comment]
Maybe this has something to do with the Azure DevOps extensions I have running?  They seem to take quite a while to get the status bar stuff set up... maybe that delays all the other extensions?  I don't know much about how the extension startup stuff works

**Comment by johnpapa** [comment]
That is possible ... You could try opening **Developer: Show Running Extensions** to see if there is something slowing you down.

**Comment by tommck** [comment]
Azure Repos extension is taking 24 SECONDS to start.. nice

**Comment by tommck** [comment]
So, at worst, this is a super-low-priority (not bothering to fix) kind of problem, since we get a menu item to run a command, yet the command never gets run.  Not sure if that's your problem or not (VS Code is probably not ever delivering the message to your extension)

**Comment by johnpapa** [comment]
ok - will close for now.

**Comment by DillPickle80** [comment]
@tommck I'm curious, i've had this problem as well lately, also i find Peacock to considerably slow down VSCode startup, but i'm also suspecting it might be actually caused by another extension being laggy.  Do you happen to use the Python extension by any hazard? Maybe doing so on a remote server, using Remote-SSH or something else?

**Comment by tommck** [comment]
@DillPickle80 I don't have the Python extension installed.  Also, the performance problems seem to have resolved themselves for me, but, choosing any color but the first does take a few extra seconds for me as well while other extensions are starting up.  I feel like there's a timing issue with the extensions.  Currently I have a lot of extensions installed, so that might affect things
