### ISSUE TITLE
v3.7.1 highjacks VS Code's "delete line" shortcut

### ISSUE THREAD

**Issue by acidoxee** [johnpapa/vscode-peacock#389]
**Is your feature request related to a problem? Please describe.**
Installing Peacock v3.7.1 in VS Code adds a keyboard shortcut for the "Surprise Me with a Random Color" action. This shortcut is currently `cmd + shift + K` on MacOS, which highjacks the default VS Code binding for the "Delete Line" action.

**Describe the solution you'd like**
Change Peacock's action binding to another set of keys. The [current next changelog](https://papapeacockstorage.z13.web.core.windows.net/changelog/#next) mentions the binding should be `cmd + shift + /` instead, so it may have just been a mistake? If not, would you consider changing Peacock's default binding so that users won't be affected by that? I recon the default VS Code shortcut must be one of the most used ones, so my guess is I won't be the only one stumbling upon this 😉 

**Describe alternatives you've considered**
Editing one's keyboard shortcuts solves the problem temporarily.

**Additional context**
![image](https://user-images.githubusercontent.com/23697296/81532865-70b34c00-9365-11ea-912b-48dbe5f56018.png)

**Comment by johnpapa** [comment]
Thank you @acidoxee for creating this issue!

**Comment by fredrik-lundin** [comment]
👍, just noticed this today too. Was really confused for a short while 😆 

Many extensions just exposes `commands` and let the user set `keybindings` themselves if they need them. That might be an option in this case, is this is not an essential keybinding I'd say. Just a suggestion 😃 

Thanks for this extension and all the work you do for the community!

**Comment by johnpapa** [comment]
This slipped in by mistake with another release. I removed it and it has been re-released.
