### ISSUE TITLE
Title and status bar borders

### ISSUE THREAD

**Issue by rudotriton** [johnpapa/vscode-peacock#397]
On the status bar I have a button for "Remote Host" which I noticed isn't flush with the top edge of the bar anymore. I thought there is an issue with the button's alignment, I did some digging and played around with workbench customizations, eventually I found #377. As a result even if the theme doesn't have a status bar border, it is added:

<img width="100%" alt="Status bar border" src="https://user-images.githubusercontent.com/14181026/83283290-a5d3f100-a1e3-11ea-8f80-44a00704f0cd.png">

This is what it looked like before and what it looks like when I remove the Peacock's border setting from the workspace settings:

<img width="100%" alt="Status bar border" src="https://user-images.githubusercontent.com/14181026/83283658-3c081700-a1e4-11ea-9304-c203d184c663.png">

For reference here is a theme that does have a border (Peacock's colored border is still turned off):

<img width="100%" alt="Status bar border" src="https://user-images.githubusercontent.com/14181026/83285249-9904cc80-a1e6-11ea-9403-e9f195a9277e.png">

Above the theme's own border doesn't stand out as much, since the border color is effectively coordinated with the theme color.

I read through the aforementioned issue, however, I fail to understand why it was an issue in the first place, because the author had overwritten the border colors in the user settings. Anyway, they probably had a good reason for this. 

Of course there are many ways to get around this cosmetic issue, ideally there would be an option to not paint the status bar border nor the title bar one, (someone may eventually notice that MacOS dims the title bar, but not the border and that becomes another annoyance), however, I'd like to have a discussion about what would be an appropriate solution here first. Thanks.

**Comment by johnpapa** [comment]
Thank you @rudotriton for creating this issue!

**Comment by johnpapa** [comment]
Thanks for raising this issue. I see your points and I agree that it looks like we may need to make a change.

I'd like to avoid introducing more settings and configuration, as it adds to the code complexity/maintenance and usability for some folks. But if that's where it leads, I'll take a look.

IIRC that issue was due to the specific theme the person was using which colored additional settings. Many themes likely did this, so I wanted to make sure Peacock accounted for it. I'll have to see how this can be fixed.

It would be awesome to have you and others be test cases for this, if you are willing?

**Comment by rudotriton** [comment]
Yes, I am definitely willing to be a test case.

I'm hoping there is a more convenient way of solving it, since this adds complexity, but maybe a possibility could be to extend the "Affect Accent Borders" setting to be more configurable and allow the user to specify which borders get affected.

**Comment by johnpapa** [comment]
I added new property **Affect Status and Title Borders**, which defaults to **false**. When false, the borders will not be colored for title nor status. When true, the borders will be colored **only if** the title or status are also colored , respectively.

v3.8.0 will have this change.

**Comment by rudotriton** [comment]
thank you so much
