### ISSUE TITLE
Create and choose an icon

### ISSUE THREAD

**Issue by johnpapa** [johnpapa/vscode-peacock#4]

**Comment by josephrexme** [comment]
![Peacock logo 1](https://res.cloudinary.com/strich/image/upload/v1550845036/Peacock_zyiyxo.jpg)

**Comment by johnpapa** [comment]
Neat!


Can we try a different color? The purple is hard to read on the black (IMO)

Maybe drop the "vscode". it's not an official extension, and i dont want to give the wrong impression

**Comment by josephrexme** [comment]
Will make those changes. I also just made this as a song option
![Peacock logo 2](https://res.cloudinary.com/strich/image/upload/v1550847021/Peacock-2_dgfnpn.jpg)

**Comment by josephrexme** [comment]
Here

![Peacock Green](https://res.cloudinary.com/strich/image/upload/v1550847296/Peacock-green_rfbqqk.jpg)

**Comment by josephrexme** [comment]
In SVG and PNG

[SVG](https://res.cloudinary.com/strich/image/upload/v1550847748/Peacock_e0x84v.svg)

[PNG](https://res.cloudinary.com/strich/image/upload/v1550847662/Peacock_eexmnh.png)

**Comment by johnpapa** [comment]
png is perfect. do you want to make the PR?

1. remove the png in the resources folder
2. name the new file `peacock-icon.png`
3. set this here https://github.com/johnpapa/vscode-peacock/blob/master/package.json#L13
4. add an entry to CHANGELOG.md

**Comment by josephrexme** [comment]
Sure! I'll do that

**Comment by josephrexme** [comment]
Done with #10

**Comment by johnpapa** [comment]
merged! thanks!

adding credits soon, too
