### ISSUE TITLE
New Setting for Saving Named Colors

### ISSUE THREAD

**Issue by plambhsa** [johnpapa/vscode-peacock#40]
I don't know if this is even possible, but it'd be cool to be able to add saved color names. So, if I have a color I want to reuse, I could save that and have it then pop up as a menu selection.

> Peacock: Save New Color Name
- Select this option
> Peacock: Enter Color Name
- My Saved Color
> Peacock: Enter Color Value
- #aaaaaa 

Then, the next time I want to use that, I can load the "My Saved Color" option right from Peacock.

If you need any clarifications, let me know. Hopefully I explained it clearly enough.

**Comment by johnpapa** [comment]
neat idea. if someone wants to map out how this would work, i'd be willing to review a plan (before a PR)

**Comment by johnpapa** [comment]
I could see this working as:

### Saving a color

- User selects menu option `Peacock: Save a Preferred Color`
- User is prompted to Enter Color Name or Hex value
- User enters `#aaaaaa`
- The color name is added to an array in user settings `peacock.savedColors` in user `settings.json`

### Selecting a preferred color

- User selects `Peacock: Change to a Preferred Color`
- User is prompted with the list from `peacock.savedColors` 


I think these could be different features. For example, the latter doesnt require the former. 

Thinking this through ...

**Comment by johnpapa** [comment]
im going to make a new issue for the selection part of this.

### Selecting a preferred color
* User selects `Peacock: Change to a Preferred Color`
* User is prompted with the list from `peacock.savedColors`

**Comment by plambhsa** [comment]
Yeah, that's basically what I was thinking of as well for how this would work. I just wasn't sure on the internals of VS Code and how you do that. I'll try and figure some of it out too to contribute!

**Comment by johnpapa** [comment]
@plambhsa check out the PR #42

**Comment by johnpapa** [comment]
v0.3.0 implements the selection of preferred colors.

manually editing settings is pretty standard for adding settings. I think I'll close this one for now.

thanks for the contributions!

**Comment by plambhsa** [comment]
Nice, thanks!
