### ISSUE TITLE
VS code does not set colors automatically when opening into a folder on remote

### ISSUE THREAD

**Issue by benlhy** [johnpapa/vscode-peacock#403]
**Versions (please complete the following information):**

- OS: Windows
- VS Code version 1.46.1
- Peacock Version 3.7.2

**Describe the bug**
If it is opened into a folder on remote, the colors will not change, even though they might be set previously. In the docs it is noted that Peacock only works in a workspace, but it also works outside of a workspace. You can set colors and they are saved in settings.json. However the colors are not set when you access the remote target again, although you can trigger the colors by using Peacock's `Peacock: Enter a color` command once and then the settings.json file is read and the colors are updated as per normal.

**To Reproduce**

1. Access remote workspace that doesn't have a .code-workspace extension, ie only settings.json in the .vscode folder
2. If you set colors using Peacock's `Peacock: Enter a color` command, the color will be set in settings.json and the colors will change. However if you exit and access the remote target again the colors will not be set even though the settings.json file is created.

**Expected behavior**
1. Expected that the colors set by Peacock will be saved and displayed on each session.

**Screenshots**

**Additional context**
1. This can be solved by creating a .code-workspace file instead of a settings.json file and accessing that remote workspace instead of accessing the root folder in the remote target.
2. The text in the settings.json folder is greyed out when a .code-workspace file is used.
3. Perhaps the docs on the remote section can be updated to note this if it is expected behavior?
4.  Related to #333, Peacock works without a workspace, but won't persist.

**Comment by johnpapa** [comment]
Thank you @benlhy for creating this issue!

**Comment by benlhy** [comment]
![image](https://user-images.githubusercontent.com/19624222/86259164-44da7700-bbee-11ea-8dc2-b717c4a20254.png)
This is what I meant by the greyed out text.

**Comment by robhaswell** [comment]
I have the same issue, except my status bar adheres to the color configuration but not anything else. I am using WSL but I can reproduce this on my mac.

https://www.youtube.com/watch?v=WKlYo8oZTIk

**Comment by benlhy** [comment]
> 
> 
> I have the same issue, except my status bar adheres to the color configuration but not anything else. I am using WSL but I can reproduce this on my mac.
> 
> https://www.youtube.com/watch?v=WKlYo8oZTIk

Hi can you try accessing your WSL instance as a workspace and confirming if that rectifies the issue?

**Comment by robhaswell** [comment]
As a workaround that does seem to apply the correct peacock colouring, however I don't want to have to set up workspaces in order to fix this. Does this help you resolve the underlying problem?

**Comment by benlhy** [comment]
Yep, Peacock works as expected once I open locations as workspaces. I spent some time trying to find out why my changes weren't saving as Peacock also works (to a limited extent) without workspaces.

**Comment by johnpapa** [comment]
Peacock only works in workspaces. This is due to how the settings.json file in the .vscode folder only gets created and applied for workspaces.
