### ISSUE TITLE
Color Palette

### ISSUE THREAD

**Issue by ahmadawais** [johnpapa/vscode-peacock#41]
A new feature could be a setting where one could define an array of colors that go well with a theme. E.g. with my 🦄 Shades of Purple theme I'd use different shades of purple, yellow, and pink. Choosing that option would choose a color from that predefined array of colors.

Option: Random from the Color Palette

Setting: 

```json
"peacock.colorPalette": [
		"mediumpurple",
		"slateblue",
		"mediumslateblue",
		"#BADA55"
	],
```

Looking forward, peace! ✌️

**Comment by musicfuel** [comment]
This seems very similar to #40 and could likely be accomplished with the same functionality.

**Comment by johnpapa** [comment]
I will close this in favor of #40 


if you feel it is different then please let me know
