### ISSUE TITLE
Save settings into a custom file or path beside `.vscode/settings.json`

### ISSUE THREAD

**Issue by rohmanhm** [johnpapa/vscode-peacock#410]
**Is your feature request related to a problem? Please describe.**
My issue is I do commit my `.vscode/settings.json` but I don't want to commit my peacock color customisation into it because each dev their own preference.

**Describe the solution you'd like**
I think it would be nice if we have something like `.vscode/peacock.json` file config which I can add into my `.gitignore` settings.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by johnpapa** [comment]
Thank you @rohmanhm for creating this issue!

**Comment by alexgv99** [comment]
+1


796/5000
Hello ... it is cool to be able to customize the IDE color by project, which gives us a visual feedback on which project we are currently working on ... but when we are working as a team, everyone has their own preferences ... It would be good to have a way of not interfering with the preferences of other developers, without losing the advantage of sharing important lint and formatting preferences in the project. Whether it's a file for peackock settings, as suggested by @rohmanhm, or maybe a way to selectively use workspace settings depending on who we are ... I'm not sure if that's a good idea ... I think that the extension settings file is the best.
Anyway ... thanks for the work on that extension and thanks for sharing it.

**Comment by LorisZ** [comment]
Agree with what @rohmanhm says, I would only like to add that the same logic goes for any `workbench.colorCustomizations` that peacock currently saves in the workspace settings. Because if it uses a separate file for the peacock settings, then the same should go for the `workbench.colorCustomizations` section as it would affect other users in the same way, even if they don't have the extension. Not even sure if that's possible inside the scope of the extension though, but one without the other would not make much sense, IMO.

**Comment by pschaeflein** [comment]
I feel the extension should provide for User/Workspace settings just like VSCode.  IMO, the solution for the original poster is User settings.

**Comment by johnpapa** [comment]
thanks for the feedback. please see #7 ... this is our issue for this topic and there is a dependency on a vs code feature. You can read the comments in that issue thread about several ideas and why a separate file wont work at this time.

**Comment by giacomorebonato** [comment]
As workaround for this, is there way of settings color for each project from the user `settings.json`?
