### ISSUE TITLE
Bad link on the About Peacock page

### ISSUE THREAD

**Issue by adriatic** [johnpapa/vscode-peacock#423]
**Versions (please complete the following information):**

OS and vs code versions are irrelevant

- Peacock Version [e.g. 2.5.2]

**Describe the bug**
The picture is the best description of the bug:

![image](https://user-images.githubusercontent.com/2712405/99732015-bd9e7a80-2a8c-11eb-919b-8fb9e8d4988e.png)

The current value of the link: https://github.com/johnpapa/vscode-peacock/edit/feature/vuepress/docs/about/history.md

**Comment by johnpapa** [comment]
Thank you @adriatic for creating this issue!

**Comment by adriatic** [comment]
I often use such a feature - so I assumed you would care to fix it. 

Allow me to use this opportunity to:
- state that both the VS Code Peacock feature is incredibly beautiful (you do have the artistic side of yourself
- it would be nice to know how many instances of VS Code you typically run - and what is your machine's power
- tell that I found this app by searching for a consistent document on using Vuepress to build a documentation site.

I am watching you from afar for many years and you still show significant improvements in your work. 😃

**Comment by adriatic** [comment]
There is another bad link on https://papapeacockstorage.z13.web.core.windows.net/about/license.html - shown below:

![image](https://user-images.githubusercontent.com/2712405/101095881-a41d2880-358c-11eb-8b5e-7b50e3e54a56.png)

P.S. A conclusion that I am searching for bad links would be inaccurate.

**Comment by willpower232** [comment]
I think it affects every page because this line in the config is wrong, presumably it could be updated or commented out to resolve them all in one go

https://github.com/johnpapa/vscode-peacock/blob/eee01915588213f036feb2405106da4fc8ff329a/docs/.vuepress/config.js#L47

**Comment by johnpapa** [comment]
Would you like to make a PR for this ?

**Comment by adriatic** [comment]
As I really appreciate the John's approach to code development (near perfection) I found two more bad links

1. https://github.com/johnpapa/vscode-peacock/raw/master/resources/hero.png
2. https://github.com/johnpapa/vscode-peacock/raw/master/resources/peacock-icon-small.png

on the Marketplace page (https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock&wt.mc_id=vscodepeacock-github-jopapa)

I will come back to this issue (#423) as son as I get out of the current squeeze on my time. If nobody else fixes these (three imperfections now) I will create the PR.

**Comment by johnpapa** [comment]
fixed in #468
