### ISSUE TITLE
Title bar colorization doesn't work on macOS Big Sur

### ISSUE THREAD

**Issue by monsieurm** [johnpapa/vscode-peacock#425]
**Versions (please complete the following information):**

- OS: macOS 11.0.1
- VS Code version 1.51.1
- Peacock Version 3.9.1

**Describe the bug**
Title bar colorization doesn't work until Big Sur update.
Work for Accent borders
Work for Activity bar
Not work for Debugging Status Bar
Not work for Status and Title Borders
Work for Status Bar
Not work for Tab Active Border
Not work for Title Bar

**To Reproduce**

1. Go to 'Peacock Settings'
2. Click on differents checkboxes to enable/disable affectations
3. See no changes

**Expected behavior**
I use ony title bar colorization, and it's not colorized anymore

**Comment by johnpapa** [comment]
Thank you @monsieurm for creating this issue!

**Comment by pn11** [comment]
@monsieurm
You can check the settings mentiond in https://github.com/johnpapa/vscode-peacock/issues/34#issuecomment-469688404. Though I am still using macOS Catalina, setting `window.nativeTabs: true` and `window.nativeFullScreen: false` worked for me.

**Comment by monsieurm** [comment]
@pn11 Thanks for your response, but it doesn't work for me. Maybe because Big Sur 👎🏻

**Comment by johnpapa** [comment]
I am unable to reproduce the issue. If others are experiencing this, please help provide some more details so we can determine what may be the cause/fix

**Comment by Phojie** [comment]
Anyone solve this issue on the latest OS ?

**Comment by johnpapa** [comment]
> Anyone solve this issue on the latest OS ?

Sadly, I've never been able to reproduce the issue nor received any info that would pinpoint it.

**Comment by monsieurm** [comment]
How can I help you with this bug, because sadly I don't use this extension anymore 👎🏻

**Comment by monsieurm** [comment]
Hurray ! I have discover what's wrong !!

With the latest release of Code, there is a new feature, "Window: Command Center". To activate it, the "Window: Title Bar Style" option must be set to "Custom". In my case it was set to "Native".

I changed it and then I reactivated the extension to see if it worked... And now I don't know why but it works again.
