### ISSUE TITLE
Will peacock add the new sash.hoverBorder?

### ISSUE THREAD

**Issue by ff6347** [johnpapa/vscode-peacock#427]
In VSCode 1.52.0 we've gotten the new setting `"sash.hoverBorder"` [release note](https://code.visualstudio.com/updates/v1_52#_sash-hover-border-color) Will Peacock use this?

**Comment by johnpapa** [comment]
Thank you @ff6347 for creating this issue!

**Comment by johnpapa** [comment]
Thanks for asking. Today the behavior is to color it using, ironically, the same color as the activity bar. We could arguably say it should be the same as that ... or the same as the title or status bars. Which one though?

I'm open to ideas here ... but for now, I think I'll keep it as is.

I welcome all feedback on this. Love to hear other perspectives on the sash.

**Comment by ff6347** [comment]
> Today the behavior is to color it using, ironically, the same color as the activity bar.

Does it? For me with peacock 3.9.1 it seems to use a default vscode color.

![sash-hover-border](https://user-images.githubusercontent.com/315106/128681499-ac0e7187-3907-428a-a2fc-aaad5a925ffa.gif)

**Comment by johnpapa** [comment]
Thanks for showing this. I see this behavior now too. I would love some community help on aN enhancement for this. 

I'll mark it as "help wanted" and I welcome a PR for the change, the test, and the changelog and readme updates.

**Comment by ff6347** [comment]
🚀
