### ISSUE TITLE
Base color transparency

### ISSUE THREAD

**Issue by ferretwithaberet** [johnpapa/vscode-peacock#428]
**Is your feature request related to a problem? Please describe.**
I find the random/default colors of peacock to be too bright/neon for my taste.

**Describe the solution you'd like**
A `peacock.baseOpacity` setting that could be either a 0 to 1 float(Example: 0.5) or a 2 digit hex number(Example: "7F") that would be appended to the base random/default color.

**Describe alternatives you've considered**
None

**Additional context**
This might make this extension blend better with the user's color theme as the peacock color will combine with the editor's bar color. I already tested adding the opacity myself to the `peacock.color` setting and it works.

**Comment by johnpapa** [comment]
Thank you @ferretwithaberet for creating this issue!

**Comment by johnpapa** [comment]
thanks for filing this. transparency would be fun! but I dont see any API for this at this time, so let's close it til such time it is available.
