### ISSUE TITLE
Plugin Homepage - Images do not load

### ISSUE THREAD

**Issue by ashtonpaul** [johnpapa/vscode-peacock#429]
**Versions (please complete the following information):**

- OS: macOS
- VS Code version: n/a
- Peacock Version 3.9.1

**Describe the bug**
The [peacock icon](https://github.com/johnpapa/vscode-peacock/raw/master/resources/peacock-icon-small.png) and the [hero image](https://github.com/johnpapa/vscode-peacock/raw/master/resources/hero.png) are not displaying on the VS-code plugin marketplace for this [plugin](https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock&wt.mc_id=johnpapa-github-jopapa)

**To Reproduce**

1. Go to https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock&wt.mc_id=johnpapa-github-jopapa
2. Scroll down
3. See error

**Expected behavior**
The images for the small peacock icon and the hero image should display

**Screenshots**
![Screen Shot 2021-01-07 at 2 33 58 PM](https://user-images.githubusercontent.com/403329/103942533-2ce03480-50f6-11eb-8e2b-ba7fde4e87d8.png)
![Screen Shot 2021-01-07 at 2 34 04 PM](https://user-images.githubusercontent.com/403329/103942548-32d61580-50f6-11eb-9f30-c5bf3100bcd3.png)

**Additional context**
None

**Comment by johnpapa** [comment]
Thank you @ashtonpaul for creating this issue!

**Comment by willpower232** [comment]
Looks like its referring to the raw endpoint incorrectly,
`https://github.com/johnpapa/vscode-peacock/raw/master/resources/peacock-icon-small.png`
should be 
`https://raw.githubusercontent.com/johnpapa/vscode-peacock/main/resources/peacock-icon-small.png`

**Comment by johnpapa** [comment]
interested in making a PR ?

**Comment by willpower232** [comment]
I did briefly have a look to be honest but I wasn't initially familiar with the structure of the files so wasn't sure where to start :sweat_smile:

**Comment by willpower232** [comment]
:pray:
