### ISSUE TITLE
Project has no license

### ISSUE THREAD

**Issue by spoenemann** [johnpapa/vscode-peacock#430]
This project doesn't have any license. Please add one, preferably an [open source license](https://opensource.org/licenses) such as MIT.

A license is mandatory for publishing your extension to [Open VSX](https://open-vsx.org/). Its publishing tool [ovsx](https://www.npmjs.com/package/ovsx) offers to automatically add the MIT license when you try to publish without license. See the [Open VSX Wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) for more details.

**Comment by johnpapa** [comment]
Thank you @spoenemann for creating this issue!

**Comment by johnpapa** [comment]
thanks, just added

**Comment by spoenemann** [comment]
Great!

One more detail: the package.json says `"license": "SEE LICENSE IN LICENSE.md"`, but the file is actually named `LICENSE`. I would suggest to change the entry to `"license": "MIT"`.
