### ISSUE TITLE
Color does not change at startup

### ISSUE THREAD

**Issue by focussing** [johnpapa/vscode-peacock#434]
**Versions (please complete the following information):**

- OS: mac
- VS Code version latest
- Peacock Version latest

**Describe the bug**
**To Reproduce**
When I do "New window" from VScode menu the color changes nicely => perfect
If I press rightclick on the VScode icon in the taskbar and do "New window" => perfect
If I press rightclick on the VScode icon in the taskbar and press a previous projected => color does not change

**Comment by johnpapa** [comment]
Thank you @focussing for creating this issue!

**Comment by johnpapa** [comment]
closing due to inability to repro.
