### ISSUE TITLE
[Feature] Integration with project manager extension 

### ISSUE THREAD

**Issue by UsulPro** [johnpapa/vscode-peacock#435]
Hey! Thank you for this awesome extension!

I wonder how hard would it be to integrate it with another great extension - https://github.com/alefragnani/vscode-project-manager

Would be nice to highlight folder icons to selected colors

![image](https://user-images.githubusercontent.com/14885189/106647215-b113c380-659f-11eb-86b5-2d104377edc2.png)

**Comment by johnpapa** [comment]
Thank you @UsulPro for creating this issue!

**Comment by johnpapa** [comment]
that would be great. if you have an idea for it, please suggest perhaps in a PR.
