### ISSUE TITLE
RemoteHub (builtin preview extension) not coloured

### ISSUE THREAD

**Issue by t-ricci-enhancers** [johnpapa/vscode-peacock#438]
**Versions (please complete the following information):**

- VS Code version 1.55.0-insider
- Peacock Version 3.9.1

**Describe the bug**
The new status bar icon (bottom left) of the RemoteHub vscode buildin (preview) extension is not coloured by Peacock (shows the normal UI background/foreground themed colour, black in my case instead of being coloured red by Peacock). When mouse-hovered it shows the correct background and foreground colours.

See attached screenshot

**To Reproduce**
Update to latest VSCode Insiders

**Expected behavior**
Peacock should colour the status bar icon of RemoteHub as defined

**Screenshots**
![Screen Shot 2021-03-22 at 11 53 34](https://user-images.githubusercontent.com/34159726/111979804-c9b34b00-8b05-11eb-898c-f7d0733f6b25.png)

**Comment by johnpapa** [comment]
Thank you @t-ricci-enhancers for creating this issue!

**Comment by johnpapa** [comment]
Thanks for reporting this ... I havent been able to look into it yet, but if someone in the community wants to try, I welcome the help. Otherwise, I will get to it when time frees up

**Comment by willpower232** [comment]
![image](https://user-images.githubusercontent.com/1619102/116052655-bc8ffb80-a671-11eb-8a69-40969b57440c.png)

It is possible this has been resolved by the time the release was finalised, unless its insider-specific

**Comment by t-ricci-enhancers** [comment]
I haven't tested on the stable release but,

this is insiders without any color set on peacock:

![Screen Shot 2021-04-26 at 10 45 43](https://user-images.githubusercontent.com/34159726/116055387-eef32600-a67c-11eb-84e8-0bc648230e33.png)

this is insiders with blue set as color on peacock:

![Screen Shot 2021-04-26 at 10 45 53](https://user-images.githubusercontent.com/34159726/116055439-fb777e80-a67c-11eb-88f0-54bb81476e25.png)

I Expected the green icon to be on a blue background (possibly changing from green to white if the contrast isn't enough??)

**Comment by willpower232** [comment]
Ah so insider specific then, that is interesting. Just to be sure, is there an insiders version of the remote plugin or is that the mainstream release?

**Comment by johnpapa** [comment]
Yes, can you add to the changelog as well?
