### ISSUE TITLE
Stroing settings in a seperate file 

### ISSUE THREAD

**Issue by RezaRahmati** [johnpapa/vscode-peacock#440]
**Is your feature request related to a problem? Please describe.**
In our enterprise company to have same coding styles we store the ".settings" file in source control, since the peacock configuration is going to be stored in that file , it goes to source control, then different devs can't have their own custom colors. Wondering if it's possible to define the file peacock stores the settings?

**Describe the solution you'd like**
Having a settings for file name or storing the settings in .peacock file in vscode folder

**Comment by johnpapa** [comment]
Thank you @RezaRahmati for creating this issue!

**Comment by RezaRahmati** [comment]
@johnpapa is there any workaround for this, since it's annoying the whole dev team and I have to stop using it if there is no workaround

**Comment by johnpapa** [comment]
Thanks for commenting. To avoid duplication, please see open issue #7
