### ISSUE TITLE
peacock for vscode windows (not the OS)

### ISSUE THREAD

**Issue by soneji** [johnpapa/vscode-peacock#441]
Hiya

I'm not sure whether this has been asked before but I was wondering whether it is possible to have the features of peacock across different vscode windows. I don't really use vscode workspaces

**Comment by johnpapa** [comment]
Thank you @soneji for creating this issue!

**Comment by willpower232** [comment]
Peacock stores its settings in a file that is part of the folder (or workspace) you have open so if you set it in one folder and open a new folder in a new window then it will have your default theme until you set a colour again.

**Comment by soneji** [comment]
Is there any way to make it automatically choose a random colour for every new vscode window/folder?

**Comment by willpower232** [comment]
Not to my knowledge

**Comment by johnpapa** [comment]
It only works if a workspace is open. When you open a folder, there is a single workspace by default. 

This extension cannot work without the vscode folder.
