### ISSUE TITLE
Is it possible to add some colorpicker interface to "Enter a color" or other command?

### ISSUE THREAD

**Issue by belonesox** [johnpapa/vscode-peacock#450]
Is it possible to add some colorpicker interface to "Enter a color" or other command?

**Comment by johnpapa** [comment]
Thank you @belonesox for creating this issue!

**Comment by johnpapa** [comment]
At this time I am unaware of any color picker API for vs code. If once gets created, I would love to have a contribution for it.

Thanks!

**Comment by rickvian** [comment]
i think this issue should be left open, it will be convenient so i don't need to pick color from google and copy it over

**Comment by dsiddharth2** [comment]
@johnpapa  This would be a really good feature to have, I would want to open this again if you are okay. Below is the approach,

## Approach

Reuse Peacock's existing apply path. Change only how the user chooses the color.

### Entry

**Command:** `Peacock: Change to a Favorite Color`

This is the same command users already use.

---

## Step 1 — Quick Pick for Preset Colors

Present the existing `peacock.favoriteColors` as preset options.

### Options

* Show the existing `peacock.favoriteColors` as preset rows.
* Each row should display:

  * Color swatch
  * Color name
  * Hex value
* Add one additional item at the bottom:

  **Custom color…**

### Behavior

* **Favorite selected** → Continue through Peacock's existing flow:

  * `applyColor`
  * `updateColorSetting`
* **Cancel / Esc** → Do nothing.

  * Restore the current color, consistent with the existing favorite-color preview behavior.

---

## Step 2 — Custom Color Webview

Only open this step when the user selects **Custom color…**.

### Implementation

Use the public VS Code API:

`vscode.window.createWebviewPanel`

### UI

Display a small card containing:

* Native color picker: `<input type="color">`
* Hex color text field
* **Cancel** button
* **Apply** button

### Behavior

* The native color well and hex input should remain synchronized.
* Changing either value updates the other.
* Invalid hex values should:

  * Display an error
  * Disable/block **Apply**

### Apply

On **Apply**, use Peacock's existing apply path:

`enterColorHandler` → `applyColor` → `updateColorSetting`

### Cancel / Close

* **Cancel** → Restore the color that was active before opening the custom picker.
* Closing the webview panel without applying → Also restore the original color.

---

## Summary

The implementation reuses Peacock's existing color application and persistence logic.

The only new behavior is the color-selection experience:

1. The existing command opens a Quick Pick.
2. Users can select an existing favorite color directly.
3. Users can select **Custom color…** to open a custom color picker with hex input.
4. Both preset and custom colors ultimately use the existing Peacock apply/update path.
