### ISSUE TITLE
Peacock creates new settings.json File not using default one

### ISSUE THREAD

**Issue by pwahlmueller** [johnpapa/vscode-peacock#453]
**Versions (please complete the following information):**

- OS:: Windows 10.0.14393
- VS Code version 1.57.0
- Peacock Version 3.9.1

**Describe the bug**
Peacock automatically creates an .vscode\settings.json with WorkbenchColorCustomization and peacock properties inspite there is also a setting.json in C:\Users\<User>\AppData\Roaming\Code\User

**To Reproduce**

1. Open VScode with a settings.json in the Appdata directory (default?)
2. Use Peacock "Surprise me with a Color"
3. See new File created

**Expected behavior**
Would expect, that the existing settings.json is used.

**Comment by johnpapa** [comment]
Thank you @pwahlmueller for creating this issue!

**Comment by willpower232** [comment]
Peacock only styles the current editor which means it has to create a file in each workspace, if you want to apply the same style to all your editors, you can probably copy the settings into your main settings and then remove the extension if you don't need it again.

**Comment by pwahlmueller** [comment]
So I understnad, that .vscode\settings.json is for each workspace and the ..\Appdata\..\settings.json is a file for all workspaces. 
Accordingly, the behavior is desired, as Peacock styles the Workspace.

**Comment by jovyllebermudez** [comment]
> So I understnad, that .vscode\settings.json is for each workspace and the ..\Appdata..\settings.json is a file for all workspaces. Accordingly, the behavior is desired, as Peacock styles the Workspace.

Hi Pwahlmueller, 
I can suggest a thing, 
it is indeed an issue that our workmates might don't like their VSCode color get changed by us.

We can "disable (workspace)" this extension to the particular project/workspace, this saved me. My workmate mocked me with purple vscode getting into the production.
