### ISSUE TITLE
Show last color (for a second) when starting different workspace

### ISSUE THREAD

**Issue by doc-code-hub** [johnpapa/vscode-peacock#454]
- OS:                       Windows 10
- VS Code Version: 1.57.1
- Peacock Version:  3.9.1

**Describe the bug**
Peacock shows the active color in the last workspace for about a second before applying the one belonging to the workspace.

I'm not entirely sure it's peacock's fault and not maybe VS Code itself, but I think it's fair to report it to you in case you can do something about it.

**To Reproduce**

1. Setup different colors for different workspaces 
2. Open and close the first workspace
3. Open the second workspace 
4. You will see for about a second the first workspace color, then the right color will be applied.

**Expected behavior**
Only the VS Code theme should show up until the correct color belonging to the workspace is loaded.

**Reflections**
I am afraid that the problem could be attributable to VS Code, which keeps loaded the last values present in the settings.json of the previous workspace.

In this case I think you should close this issue and open a new one for VS Code regarding this issue.

Hope this help!

Good job anyway!

**Comment by johnpapa** [comment]
Thank you @doc-code-hub for creating this issue!

**Comment by willpower232** [comment]
I think it will be something along the lines of it takes vscode a little while to open the folder/workspace and process the local file which has the colour specifics in. I've certainly noticed it myself but it hasn't been noticeably different from how long the rest of the UI takes to populate.

It would be interesting to time it with and without the rest of the extensions you have to see if the load time improves.

**Comment by doc-code-hub** [comment]
However, since the interface has not yet activated, as you rightly say, I believe that the previous peacock colors should not be seen at this stage...

Do you think it would be possible to insert a listener on the closing of VS Code, going to remove the style set at the initialization based on the settings, to avoid that this color persists in this short period of time during startup?

**Comment by willpower232** [comment]
Peacock just generates the colour values, the user has to wait for vscode to read the local config file and apply the config changes.

If you don't have a stopwatch handy, you would have to refer to their own github repo for information on how to build and debug it directly.

**Comment by johnpapa** [comment]
I'm not sure how to stop that delay as this is vs code remembering the last setting before it actives and reads the new settings.
