### ISSUE TITLE
Element Adjustments adjust granular colors

### ISSUE THREAD

**Issue by brhubbar** [johnpapa/vscode-peacock#456]
I would like my active selection on the activity bar to be more distinct. I can do this by darkening the `activityBar.activeBackground` relative to `activityBar.Background`. However, Peacock won't do this automatically, nor does it save the modification I make. 

Current Behavior:

![Peacock's Behavior](https://user-images.githubusercontent.com/55867501/124405740-08f85700-dd05-11eb-8cd1-85c08b853036.png)

Desired Behavior:

![My desired behavior](https://user-images.githubusercontent.com/55867501/124405811-334a1480-dd05-11eb-8472-e140f8344f80.png)

**Describe the solution you'd like**

I would like to be able to control this for sub elements of the `activityBar`, `statusBar`, and `titleBar`, in the already existing manner - something like:

![Desired settings approach](https://user-images.githubusercontent.com/55867501/124405961-a05daa00-dd05-11eb-94cc-eae95982232f.png)

**Comment by johnpapa** [comment]
Thank you @brhubbar for creating this issue!

**Comment by willpower232** [comment]
this reminds me of #448 but its interesting that what you have tried isn't working

**Comment by johnpapa** [comment]
closing for the separate issue
