### ISSUE TITLE
[idea] Option to only show colored bottom status bar

### ISSUE THREAD

**Issue by CodisRedding** [johnpapa/vscode-peacock#457]
I find the colors to be distracting (even when darkening the colors), but I do love the idea. If there was a way to only color the bottom status bar instead of the left and top as well it would be less distraction and still just as helpful when choosing between instances. Could this easily become an option?

**Comment by willpower232** [comment]
At the minute you would have to change the file yourself after running peacock but I can see the appeal of this.

**Comment by CodisRedding** [comment]
It's mainly the left side that causes the distraction for me. Having the option to set a specific one would be ideal, but an option to just remove the left side would work too. 

I'll manually edit the file for now. Thanks @willpower232

**Comment by johnpapa** [comment]
Have you checked the docs or the settings to see if the features to enable or disable the coloring of different aspects covers what you want? For example you can choose to color the status bar but not the side bar or title bar.

**Comment by willpower232** [comment]
Oh my goodness I knew this was familiar https://www.peacockcode.dev/guide/#affected-elements sorry for the confusion!

**Comment by CodisRedding** [comment]
@willpower232 that's what I get for not RTFM! Thanks you, just what I needed.
