### ISSUE TITLE
Option to effect the color change only on the font

### ISSUE THREAD

**Issue by anandinasu** [johnpapa/vscode-peacock#460]
Hello @johnpapa ,

Thanks a lot for this wonderful extension. It is extremely useful.

**Describe the solution you'd like**
Right now we can set where all the color changes will get affected and it is great. I know very clearly that I am asking for more but would it be possible to make these changes only to the font/ foreground instead of changing the whole thing? In short, very specifically, would it be possible to have random color only on the font instead of the whole thing itself at the startup. Eg: By setting this "peacock.affectTitleBar": true and "peacock.surpriseMeOnStartup": true, the whole title bar will get a new color at the startup. Instead, I want just the font color of the title bar to be different instead of the whole title bar itself. I know that with this option "peacock.darkForegroundColor": "#15202b" we can keep one specific color, but what I am looking for is random colors.

**Describe alternatives you've considered**
I tried to delete everything except "titleBar.activeForeground" and assigned that the value of "titleBar.activeBackground". However, at every startup, everything is getting added again, which is how this extension is supposed to work. So it is understood and that's okay.

Thank You.

**Comment by johnpapa** [comment]
Thank you @anandinasu for creating this issue!

**Comment by willpower232** [comment]
I think you'll find that calling surpriseMeOnStartup always sets all properties it can as if none have been set so unless there is an advanced way of turning off all the options, I don't think you'll be able to resolve it.

That said, would it simplify things if the way of turning the properties on and off was done as a JSON list for quick and dirty editing I wonder...

**Comment by anandinasu** [comment]
Hi @willpower232 

> I think you'll find that calling surpriseMeOnStartup always sets all properties it can as if none have been set so unless there is an advanced way of turning off all the options, I don't think you'll be able to resolve it.

The rationale behind this is understood and I believe this is how it is supposed to work given the primary purpose of this extension is to randomize color.

> That said, would it simplify things if the way of turning the properties on and off was done as a JSON list for quick and dirty editing I wonder...

I feel a JSON object inside object could be used instead of a single value for keys, say for eg ```"peacock.affectTitleBar": true```. 

When ```"peacock.affectTitleBar": true``` is set, these four keys are added to my settings file:

```
"titleBar.activeForeground": ""
"titleBar.activeBackground": ""
"titleBar.inactiveBackground": ""
"titleBar.inactiveForeground": ""
```

Instead of just ```"peacock.affectTitleBar": true```, if it is something like

```
"peacock.affectTitleBar":
{
	"titleBar.activeForeground": true,
	"titleBar.activeBackground": true,
	"titleBar.inactiveBackground": true,
	"titleBar.inactiveForeground": true,
}
```

then the user will have more flexibility to set what they want right. I am not sure about simplicity as this means seeing lot more options than just one option. However, someone who knows how settings are managed and edited in vs code, they will easily catch up right?

**Comment by willpower232** [comment]
yeah something like that, an "advanced override" for the power user that wants more precise control would be Neat :tm: so it doesn't mess up existing users

**Comment by johnpapa** [comment]
This is a neat idea, thanks for sharing it. Peacock has evolved to a state where there are a lot of settings, and many users never touch them (for various reasons). The more settings I've added, the more diverse the feedback has been )some want more settings as shown here and some want far less). The right balance is what I try to strive for,

More settings significantly increases the surface area for potential challenges both with the functionality and with the usability. As such I try very hard not to add more complexity to settings, despite how much more fine tune control it may bring.

It also raises backward compat issues, which is always top of mind.

At this time I'm going to close this issue. Thank you again for raising it and clarifying the intent!
