### ISSUE TITLE
opening at the same time the same workspace local and remote flips flops the color

### ISSUE THREAD

**Issue by marco-m** [johnpapa/vscode-peacock#469]
**Versions**

- OS: macOS
- VS Code version v1.60.2
- Peacock Version v3.10.1

**Describe the bug**

If you open the same workspace in two vscode windows, one local and one with the Remote extension, the color of the two windows will become the same, with one of the two wrong (both get the remote color or both get the local color).

**To Reproduce**

1. local: create workspace and give it a color with Peacock.
2. open a second window (keep the first one, local, opened) in Remote mode, with the same workspace.
3. in the remote window, set a different Peacock color (this color is saved correctly as `peacock.remoteColor` in the code-workspace file.
4. Immediately, the first window (the local one), gets the same color of the remote one.

**Expected behavior**

I expected the local window to show the local color (`peacock.color`) and the remote window to show the remote color (peacock.remoteColor)

**Screenshots**

I am happy to provide screenshots if needed.

**Additional context**

Hello, thanks for Peacock!

I am opening this as a bug because the behavior is quite confusing. I read the many tickets about the Remote integration and the trickiness of it, so maybe what I am asking is not technically feasible. If this is the case, then the documentation at https://www.peacockcode.dev/guide/#remote-development-integration should clearly state the limitation.

I think I understand the problem: Peacock sets `workbench.colorCustomizations`, and it seems that this setting is somehow global, vscode is not able to differentiate between local and remote view.

**Comment by johnpapa** [comment]
Thank you @marco-m for creating this issue!

**Comment by marco-m** [comment]
The workaround I found is to have two code-workspace files, for example local.code-workspace and remote.code-workspace, and then open them separately. This works, although they will go out of sync.

**Comment by johnpapa** [comment]
I understand the concern, but I am not sure how to resolve this beyond separate files, which is not something easily implementable. There are other issues related to how vs code inherently handles settings files (saving to github, for example) as well.

Only one set of colors is stored at one time: remote or local.

Closing this "as designed"
