### ISSUE TITLE
Proposal: Spread the Settings to make them visible in the settings panel

### ISSUE THREAD

**Issue by JulianG** [johnpapa/vscode-peacock#47]
The settings panel could look like this:

<img width="738" alt="three separate settings" src="https://user-images.githubusercontent.com/237818/53654579-f9086e00-3c45-11e9-9640-88f820c48f66.png">

If instead of an array, we had 3 separate configuration properties:
```
    "configuration": {
      "properties": {
        "peacock.affectTitleBar": {
          "type": "boolean",
          "default": true,
          "description": "Specifies whether Peacock should affect the title bar."
        },
        "peacock.affectActivityBar": {
          "type": "boolean",
          "default": false,
          "description": "Specifies whether Peacock should affect the activity bar."
        },
        "peacock.affectStatusBar": {
          "type": "boolean",
          "default": false,
          "description": "Specifies whether Peacock should affect the status bar."
        }
      }
    }
```

**Comment by mikeerickson** [comment]
@JulianG @johnpapa Hey gang, if this change is made, please let me know as I am working on the CLI version and read these settings accordingly.

**Comment by johnpapa** [comment]
Neat idea. It seems no less hard coded than what exists today (meaning the extension only supports these already).

I like this because it uses the conventional settings UI and not a new command/menu.

Anyone else have an opinion?

**Comment by mikeerickson** [comment]
I like the direction, surely much clearer for the end user AND it promotes using the cool vscode setting UI

**Comment by johnpapa** [comment]
implemented in v.0.5.0

**Comment by JulianG** [comment]
awesome! I'll update asap!
