### ISSUE TITLE
more granular control of the Accent Borders

### ISSUE THREAD

**Issue by superole** [johnpapa/vscode-peacock#472]
I would like to have more granular control of the Accent Borders.
In particular I would like to have the sash.hoverBorder affected but not panel.border and sideBar.border.

**Is your feature request related to a problem? Please describe.**
With a dark theme in VSCode, and a bright Peacock color like #3ee808, it is distracting to have the panel.border and sideBar.border affected. Because they draw too much attention to them selves, and conflict visually with gutter elements in the editor like git status markers. But the sash.hoverBorder does not look good when it is not affected.

**Describe the solution you'd like**
I would like to have more granular control of the Accent Borders, apart from just on and off for all three properties.

**Describe alternatives you've considered**
The simplest solution for this use case would probably be to split out the sash.hoverBorder into a separate on/off option.
Another solution could be to extend the "Element Adjustments" setting to accept more than just lighten/darken, and add entries for all affected properties. It would be nice if it could accept "off" or a color-value in addition to lighten/darken/none.

**Comment by johnpapa** [comment]
closed by #479
