### ISSUE TITLE
Changelog is missing

### ISSUE THREAD

**Issue by arsinclair** [johnpapa/vscode-peacock#476]
The extension wants to update from 3.9.1 to 3.10.1 but the changelog for this version is missing. The CHANGELOG is missing in the VS Code Extensions tab, as well as here https://papapeacockstorage.z13.web.core.windows.net/changelog/#next.

**Comment by johnpapa** [comment]
Thank you @arsinclair for creating this issue!

**Comment by willpower232** [comment]
Looks like the readme link is out of date, it should be https://www.peacockcode.dev/changelog/

**Comment by johnpapa** [comment]
thanks. want to make a PR?
