### ISSUE TITLE
Extension-squatting warning?

### ISSUE THREAD

**Issue by SeaDude** [johnpapa/vscode-peacock#482]
Just a heads up, it seems someone is squatting your extension name "Peacock". (Or maybe they came first and you duplicated their extension name :) )

You may consider adding `3a. Ensure that publisher is John Papa"` to the [`/docs/guide/README.md`](https://github.com/johnpapa/vscode-peacock/tree/main/docs/guide) doc.

[Old SO post mentioning this:](https://stackoverflow.com/questions/55126683/how-is-vs-code-extension-security-handled)

**Comment by johnpapa** [comment]
Thank you @SeaDude for creating this issue!

**Comment by SeaDude** [comment]
I'll close now.

**Comment by johnpapa** [comment]
Thanks - I am not sure what action you are suggestng. Would you be interested in making a PR ?

**Comment by SeaDude** [comment]
I was suggesting you may add the text: "3a. Ensure that publisher is John Papa" to your `/docs/guide/README.md` doc so that new users don't get mixed up with the other extension also named "Peacock". 
What you end up doing is completely up to you. This ticket is all I have time for atm. 

Great extension! It comes highly recommended!
