### ISSUE TITLE
Extend the color choice to the taskbar Icon Application

### ISSUE THREAD

**Issue by ekaradon** [johnpapa/vscode-peacock#484]
Hello,

First thanks for this extension. It helps me a lot by just providing a quick feedback on what I'm viewing. Especially because I'm using the same code base in different environments. 
I use Plasma as desktop and for every VSCode, I get the same little icon, see below:
![Screenshot_20220215_140401](https://user-images.githubusercontent.com/9439390/154067599-41f86e48-2001-45f2-bc16-55db8e7c2bdd.png)
I find it a bit frustrating because I have no clue on what is what. I could certainly extends the name and get the full description of the windows but it feels like a waste of space. So I was thinking that maybe this extension would be able to customize the visual aspect of the icon? It would really be awesome if I could get a distinctive color for every VSCode. Is it possible? What do you think?

**Comment by johnpapa** [comment]
This is a great idea and one I would love to do. I do not see a way to make this happen as the API does not support it at this time for vs code. I will close this, but feel free to revisit if you find the API for it!

**Comment by ttodua** [comment]
Is very useful idea, but seems at this moment, you will need to use custom OS-native approach (i.e. whatever .exe for Windows, which modified `.icon` prop for running app on the fly).
