### ISSUE TITLE
Are these commands hard coded...

### ISSUE THREAD

**Issue by mikeerickson** [johnpapa/vscode-peacock#49]
Hey @johnpapa 

I remember these `other` commands from the early releases.  Are these commands hard-coded internally, or do they come from a config in settings?

I am working on the CLI and am trying to achieve command parity

![image](https://user-images.githubusercontent.com/183153/53671925-50521280-3c35-11e9-93d3-13db2e0cc7e7.png)

**Comment by johnpapa** [comment]
You can check the source for how this works. i think i did

**Comment by mikeerickson** [comment]
@johnpapa Better question, should these be hard coded? Do you want to keep them around moving forward since named commands now exist

**Comment by johnpapa** [comment]
not sure i follow you. can you link to what you mean?

**Comment by mikeerickson** [comment]
I will write up proposal for this as well later today or tomorrow.  Time for family time (workday over)

**Comment by johnpapa** [comment]
are you suggesting we remove these and let people add them using the peacock feature for creating named colors? i like have those available, so people can choose from something just to see how it works

**Comment by mikeerickson** [comment]
@johnpapa OK, you have the basic gist of what I am thinking.

I completely understand and agree with the reasons they exist.  My thinking is, take this a bit further and allow the end user to configure these items.  It is quite similar to named colors in theory.  The difference between these items and named colors is they appear in the initial menu (which is one step quicker).  I would personally add items such as:

- oss
- php
- javascript
- clients
- internal

These initial items could be part of the pre-configured settings, so there is something for new users to see after the first installation.

Let me know if you have questions or further information.

**Comment by johnpapa** [comment]
I think we keep them as-is for now. I may remove these entirely before I go to v1 and remove the `preview` label.

**Comment by mikeerickson** [comment]
Works for me 🤓
