### ISSUE TITLE
Premature Next Episode Prompt

### ISSUE THREAD

**Issue by dnaccarato22** [johnpapa/vscode-peacock#492]
**Versions (please complete the following information):**

- Peacock Version (Roku App)

**Describe the bug**

**To Reproduce**

1. Watch an episode of Yellowstone
2. The next episode prompt will display about 5 minutes too early
3. This error results in a premature jump to the next episode skipping the last few minutes if not canceled in time.

**Expected behavior**
This prompt shouldn't display until the credits begin.

**Screenshots**

**Additional context**

**Comment by johnpapa** [comment]
Thank you @dnaccarato22 for creating this issue!

**Comment by willpower232** [comment]
Wrong peacock :sweat_smile:

**Comment by johnpapa** [comment]
not vscode peacock :)
