### ISSUE TITLE
add support for clion or other  products of jetbrains

### ISSUE THREAD

**Issue by dalton-ly** [johnpapa/vscode-peacock#506]
good extension and i hope to use it in clion

**Comment by johnpapa** [comment]
Thank you @dalton-ly for creating this issue!

**Comment by willpower232** [comment]
do those IDEs allow you to use vscode extensions or are they completely different?

**Comment by MartinSGill** [comment]
They are completely different and would need to be written in Java. See https://plugins.jetbrains.com/docs/intellij/developing-plugins.html.

While I've never tried this, it might already be possible to do this in Jetbrains IDEs using Settings Layers.
