### ISSUE TITLE
Peacock not working

### ISSUE THREAD

**Issue by bluedusk** [johnpapa/vscode-peacock#514]
**Versions (please complete the following information):**

- OS: [e.g. mac] Apple M1 Pro
- VS Code version [e.g. 1.37.0-insiders] Version: 1.75.1 (Universal)
- Peacock Version [e.g. 2.5.2] v4.2.2

**Describe the bug**
Not sure why Peacock stopped working, no effect on any peacock releated commands. 

It shows `Activating extension` in status bar and nothing happens.

 Is there any why for me to debug it ? Any error log available. I've been using it for years, really need it work again.. Thanks a lot

**Comment by johnpapa** [comment]
Thank you @bluedusk for creating this issue!

**Comment by bluedusk** [comment]
Re-install `live share` fixed the issue for me. Hope this help others with the same issue
