### ISSUE TITLE
Remove darkForeground and lightForeground settings

### ISSUE THREAD

**Issue by musicfuel** [johnpapa/vscode-peacock#52]
The overrides for `peacock.darkForeground` and `peacock.lightForeground` seem as though they may not be useful relative to the expense of having the settings. Now that [tinycolor](https://github.com/bgrins/TinyColor) is in use following #48, it may be better to remove the complexity/overhead of the settings and either use the values as defaults or calculate new ones based on the background luminance.

The option to `keepForegroundColor` as proposed in #27 is somewhat related here. As part of this effort I propose we add that flag to settings in place of these two as a means to override the default Peacock behavior. By using the `keepForegroundColor` the user takes matters into his or her own hands and Peacock should only adjust backgrounds.

## Version Information

macOS 10.14
VS Code 1.31.1 Stable
Peacock 0.6.0

**Comment by johnpapa** [comment]
I agree with this 100%

I'm willing to take it on, but I love community contributions too. I recommend we split these into 2 PRs:

1. removing the dark and light foreground color properties

2. add the keep foreground color

**Comment by johnpapa** [comment]
closed by #53
