### ISSUE TITLE
Option to remove the color copy button on the bottom task bar

### ISSUE THREAD

**Issue by geirivarjerstad** [johnpapa/vscode-peacock#520]
Suggestion to have the possibility to remove the task bar bottom that copies the color (that I will never use, and is just bloating the IDE)

![bilde](https://user-images.githubusercontent.com/9047661/229270899-95fdfab1-2a4e-48d5-8869-25f77b55f393.png)

**Comment by johnpapa** [comment]
Thank you @geirivarjerstad for creating this issue!

**Comment by geirivarjerstad** [comment]
Ofc I discovered that I could just hide the button, after I created this issue.
