### ISSUE TITLE
Some links in docs/guide/README.md broken

### ISSUE THREAD

**Issue by hansu** [johnpapa/vscode-peacock#521]
These images embedded in the [README.md](https://github.com/johnpapa/vscode-peacock/blob/main/docs/guide/README.md) do not longer exist in the repo:

https://github.com/johnpapa/vscode-peacock/blob/main/assets/affected-settings.png
https://github.com/johnpapa/vscode-peacock/blob/main/assets/element-adjustments.png
https://github.com/johnpapa/vscode-peacock/blob/main/assets/peacock-windows.png

**Comment by johnpapa** [comment]
Thank you @hansu for creating this issue!

**Comment by hansu** [comment]
Ah yes you are right. Sorry for the noise.
