### ISSUE TITLE
Installing peacock and Neovim Ui Modifier v0.13 will cause the peacock colors to be written to vscode's user settings and will not be removed

### ISSUE THREAD

**Issue by tieniu1** [johnpapa/vscode-peacock#527]
**Versions (please complete the following information):**

- OS: [e.g. mac]
- VS Code version April 2023 (version 1.78)
- Peacock Version v4.2.2

**Describe the bug**
Install peacock and set a color for the project. Install Neovim Ui Modifier v0.13, then reset peacock and uninstall peacock, peacock's color will be written to vscode's user settings, delete the settings manually, then save the settings and they will be set back.

Solution, disable neovim ui Modifier, then manually remove the color setting of peacock from user settings.

**Comment by johnpapa** [comment]
Thank you @tieniu1 for creating this issue!
