### ISSUE TITLE
Preventing Peacock Extension from Changing Global Theme in VS Code

### ISSUE THREAD

**Issue by erbanku** [johnpapa/vscode-peacock#529]
**Is your feature request related to a problem? Please describe.**
I've been using the Peacock extension in Visual Studio Code and I've noticed that it alters the global theme settings in settings.json. While I appreciate the extension's functionality, I would prefer it not to modify the global theme, but only impact the workspace settings.

**Describe the solution you'd like**
I would appreciate an option within the Peacock extension that prevents it from changing the global theme. This would be very useful for maintaining my preferred global settings while benefiting from the workspace color differentiation that Peacock provides.

**Describe alternatives you've considered**
Another possible solution could be a setting that restricts the extension's influence to the workspace level only. This way, the global settings.json would remain unaffected by the extension.

**Additional context**
This change would greatly enhance user experience by providing more control over how the extension impacts Visual Studio Code's settings. I appreciate your consideration of this request. Thank you.

**Comment by johnpapa** [comment]
Thank you @erbanku for creating this issue!

**Comment by erbanku** [comment]
**Additional context**
Despite searching, I've yet to find a way to achieve this functionality. This feature would significantly enhance the user experience by providing more control over how the extension affects Visual Studio Code's settings. I appreciate your consideration of this feature request. Thank you.

**Comment by willpower232** [comment]
If you are using workspaces then you could copy the colours to the workspace file and confirm that still applies the colour so hopefully it is easy to identify that the window is a workspace and find that file instead

https://code.visualstudio.com/docs/editor/multi-root-workspaces#_settings
