### ISSUE TITLE
Configuration settings not respected when applying, lightening or darkening color

### ISSUE THREAD

**Issue by csandfeld** [johnpapa/vscode-peacock#535]
**Versions (please complete the following information):**

- OS: Windows 11 build 22621.2428
- VS Code version 1.83.1
- Peacock Version 4.2.2

**Describe the bug**
Configuration settings not respected when applying, lightening or darkening color.
I configured peacock with these settings:
- "peacock.affectActivityBar": false
- "peacock.affectSashHover": false
- "peacock.keepBadgeColor": true

Afterwards color is still applied to those elements when running any of these commands:
- Peacock: Change to a Favorite Color
- Peacock: Lighten
- Peacock: Darken

**To Reproduce**
1. Set Peacock configuration in user settings
   - "peacock.affectActivityBar": false
   - "peacock.affectSashHover": false
   - "peacock.keepBadgeColor": true
2. Run "Peacock: Change to a Favorite Color" to apply a color
3. Notice that colors for the elements are changed even though they are configured not to
4. Make the configuration take effect again by toggling each of the settings
5. Run "Peacock: Lighten" or "Peacock: Darken"
6. Notice that once again the elements are colorized even though they are configured not to.

**Expected behavior**

When configuring Peacock to not affect elements I expect those elements to not be affected when applying, lightening or darkening colors.

**Comment by johnpapa** [comment]
Thank you @csandfeld for creating this issue!

**Comment by csandfeld** [comment]
Set out to make a video of the issue, but was unable to reproduce it when starting out from scratch. Probably something screwy on my system after all.

Sorry for the inconvenience.
