### ISSUE TITLE
Peacock wont active

### ISSUE THREAD

**Issue by davidgeri** [johnpapa/vscode-peacock#537]
- OS: Windows_NTx64
- VS Code version [1.83.1]
- Peacock Version [4.2.2]

**Describe the bug**
Nothing happen when i select the favorite colour

**To Reproduce**
when i press f1 and choose change to favorite color, theres a notification said "activating extension" and then nothing happened

**Expected behavior**
The colour of the navbar and status bar change
![Screenshot 2023-10-27 140552](https://github.com/johnpapa/vscode-peacock/assets/56905427/79167cdc-7b30-4591-a7a0-48339038bfc3)

**Comment by johnpapa** [comment]
Thank you @davidgeri for creating this issue!
