### ISSUE TITLE
There is no any feature to switchback to previous default outer theme of vs code, its only providing some colors that can be switch between them, what if user now don't want to use it?

### ISSUE THREAD

**Issue by AliAsgharGill** [johnpapa/vscode-peacock#549]
**Versions (please complete the following information):**

- OS: [e.g. mac]
- VS Code version [e.g. 1.37.0-insiders]
- Peacock Version [e.g. 2.5.2]

**Describe the bug**

**To Reproduce**

3. See error

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by AliAsgharGill** [comment]
> I think the only way back is to manually remove `workbench.colorCustomizations` and `peacock.color` from the `.vscode/settings.json` file

Thank you! its working.

**Comment by MuhammdAhmad-19** [comment]
simply open settings of vs code by **CTRL + ,** and search for peacock in extensions and search **peacock : color** in workspace option and click on gear icon on top corner and chose reset settings..........It should work.

**Comment by AliAsgharGill** [comment]
Dine

**Comment by AliAsgharGill** [comment]
Done
