### ISSUE TITLE
'peacock.enterColor' not found

### ISSUE THREAD

**Issue by AYoubZarda** [johnpapa/vscode-peacock#553]
**Versions (please complete the following information):**

- OS: [e.g. mac]
- VS Code version [e.g. 1.37.0-insiders]
- Peacock Version [e.g. 2.5.2]

**Describe the bug**

**To Reproduce**

3. See error

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by willpower232** [comment]
Are you able to fill out the issue template rather than leave the defaults in? More context is needed here.
