### ISSUE TITLE
Adjust activity bar badge color based on background

### ISSUE THREAD

**Issue by musicfuel** [johnpapa/vscode-peacock#58]
The current colorization of the activity bar includes the background, foreground, and inactive background. The badge color that can appear over icons is still being maintained based on whatever the current theme is and is not reactive to the background color of the activity bar itself. This leads to potential usability/readability issues with the badge.

As an example, in my current Atom One Dark theme the badge color is a medium blue of #578afa. When using this in with the React Blue coloring the difference is subtle and difficult to see.

<img width="118" alt="screen shot 2019-03-06 at 9 47 29 am" src="https://user-images.githubusercontent.com/1085791/53905962-61bd6500-400f-11e9-945c-f5b9d21d76dc.png">

The problem gets even more noticeable if taking the extreme example where "Surprise Me" happened to land on the same color or even something close to it where the badge is effectively blended in.

<img width="103" alt="screen shot 2019-03-06 at 9 50 28 am" src="https://user-images.githubusercontent.com/1085791/53906034-8c0f2280-400f-11e9-8261-2c72d5099b29.png">

## Proposal

Leverage the tinycolor library to make intelligent color calculations to adjust the activity bar badge color to some form of a complementary color when the user has chosen to colorize the activity bar. The same images above with that type of logic might instead look like:

<img width="101" alt="screen shot 2019-03-06 at 1 00 27 pm" src="https://user-images.githubusercontent.com/1085791/53906245-0cce1e80-4010-11e9-9b37-3c5511695560.png">

<img width="100" alt="screen shot 2019-03-06 at 1 01 59 pm" src="https://user-images.githubusercontent.com/1085791/53906251-0f307880-4010-11e9-8bdd-35232481a9ce.png">

## Version Information

macOS 10.14
VS Code 1.31 stable
Peacock 0.7.0

**Comment by johnpapa** [comment]
I agree 100%. I was experimenting with badge - but also don;t want to go too far into intruding on someone's theme. Therefore, I think 2 things may come of this:

1. Let's move forward with your proposed changes
2. Drafting guidelines for what Peacock should affect

**Comment by musicfuel** [comment]
Awesome. I have this partially in progress since I was just playing with it a bit. I will continue on that path and submit a PR.

I also agree with the guidelines.

**Comment by johnpapa** [comment]
perfect. it's all yours

**Comment by musicfuel** [comment]
The roadmap to 1.0 item for this in #56 can be marked done.
