### ISSUE TITLE
Colorize status bar item hover background

### ISSUE THREAD

**Issue by musicfuel** [johnpapa/vscode-peacock#60]
The current colorization of the status bar includes the background and foreground. The status bar will contain several items that have hover states and most themes will set the `statusBarItem.hoverBackground` to something relatively close to the `statusBar.background` to display the interactivity of the hover state, but minimize the visual change that occurs. Currently Peacock does not set this color when the user has chosen to affect the status bar and it can result in some intense color changes on hover.

As an example, in my current Atom One Dark theme the status bar item hover background is a darker gray #2c313a. When using this in with the Angular Red coloring the difference is stark

<img width="457" alt="screen shot 2019-03-06 at 9 43 24 am" src="https://user-images.githubusercontent.com/1085791/53910215-f9738100-4018-11e9-87d6-bdf80a1e914a.png">

## Proposal

Leverage the tinycolor library to make either a slightly lighter or slightly darker hover state based on the color of the status bar background. When the user chooses to affect the status bar, the `statusBarItem.hoverBackground` would also be set to this color. With the same conditions as above that could look like:

<img width="484" alt="screen shot 2019-03-06 at 2 11 32 pm" src="https://user-images.githubusercontent.com/1085791/53910616-df866e00-4019-11e9-88aa-2702160ca13a.png">

## Version Information

macOS 10.14
VS Code 1.31 stable
Peacock 0.7.0

**Comment by johnpapa** [comment]
Agreed. This will go on the #56 Roadmap for v1.0.0
