### ISSUE TITLE
Preview the pre-selected color from the favorite colors pallette

### ISSUE THREAD

**Issue by stratosgear** [johnpapa/vscode-peacock#78]
How about the ability to dynamically preview the suggested favorite color from the Command Pallette?

So, as I scroll down the favorite colors, the pre-selected color is applied temporarily so that I can preview it.

On "Escape" the original color will be reverted.
On "Enter" the new one, would be applied.

That will help me differentiate between the available favorite colors.  It's easy to tell apart , Blue, Yellow and Red, but not so easy on colors named Acapulco, East Bay or Quicksand.

The workflow now is to blindly apply the color, and then reopen Command Pallette to select and try a new one.

Thanks for an otherwise excellent extension!

**Comment by johnpapa** [comment]
Great idea!

I've got a PR I'm working on for this. 

Thanks
