### ISSUE TITLE
Reset colors command is not pure

### ISSUE THREAD

**Issue by erhise** [johnpapa/vscode-peacock#85]
# Reset colors command is not pure

The settings.json (in workspace) is marked as modified even after a reset. It is problematic from two point of views when you are using settings.json as a collaborative settings file shared among many user.

## Version Information

vscode: 1.32.1
OS: Windows_NT x64 10.0.17134
Peacock: 1.1.0

## Repro steps

settings.json does not contain `"workbench.colorCustomizations"`.

1. Apply any color
2. Reset colors

Afterwards, these line are added and marked as git change.

```
},
    "workbench.colorCustomizations": {}
```

## The log given by the failure
--

## Mention any other details that might be useful

I am perfectly fine closing this issue and accept current behavior. But it would mean I can't use Peacock at work since we are using settings.json in our repo and can't keeping discard changes on that file on every commit :(

**Comment by erhise** [comment]
Am I also missing something, I would highly appreciate if someone could confirm that Peacock did not use settings.json at all from start, I might be wrong?

**Comment by johnpapa** [comment]
Thanks for filing this. THis is interesting ... it stems a bit from that we are currently sharing the workspace settings. And I'd love to not have this be a file that affects other users. 

Back to your point ... I agree it would be nice if "reset" put it back the way it was. But, thinking out loud, that's the same as a git command to reset it.

Would you prefer if Reset removed the `workbench.colorCustomizations` property entirely? It might solve most people's issues, as long as they didn't already have it.

Current behavior of Reset is to remove the color settings that Peacock manages. It could also do a check and if no other customizations where made (outside of peacock) then it could remove the `workbench.colorCustomizations` too.

I'm open to suggestions on this

**Comment by johnpapa** [comment]
I hacked together a PR that would address this by not only removing the colors but also removing the `workbench.colorCustomizations` in the workspace settings.

**Comment by erhise** [comment]
I understand this problem has no right or wrong and the approach is a consideration of different factors. I guess you must check "does `workbench.colorCustomizations` exists beforehand?" and save in memory to avoid the other way around with people complaining that the reset does to much.

However, different idea. How about a `.peacockrc` file?

Doesn't current approach totally leaves out the idea of sharing the settings.json file via git? Like e.g. me and my friend in a hobby project have saved some prefered settings in settings.json file. We both use Peacock, but when it comes to personal preference let's say I like to have the workspace in Angular Red and he prefers Vue Green. If I changed some setting in settings.json irrelevant to Peacock how do we handle that change?

**Comment by johnpapa** [comment]
> Doesn't current approach totally leaves out the idea of sharing the settings.json file via git? Like e.g. me and my friend in a hobby project have saved some prefered settings in settings.json file. We both use Peacock, but when it comes to personal preference let's say I like to have the workspace in Angular Red and he prefers Vue Green. If I changed some setting in settings.json irrelevant to Peacock how do we handle that change?

Yes, this is an open issue #7 

Add ing a new file would solve the write issues to the other file, but the new file is still shared (unless we gitignore it). If you have ideas on this please add them to #7.

Regarding the original issue, I PR is coming that will do this ...
> I understand this problem has no right or wrong and the approach is a consideration of different factors. I guess you must check "does workbench.colorCustomizations exists beforehand?" and save in memory to avoid the other way around with people complaining that the reset does to much.

**Comment by johnpapa** [comment]
No worries at all.

Thanks for filing this, it made me re-think the reset logic on this. I'll keep it open til I merge that PR
