### ISSUE TITLE
Feature Request: Save color per repo in user settings

### ISSUE THREAD

**Issue by granmoe** [johnpapa/vscode-peacock#89]
Our team was excited about this extension, but now we don't want to use it because the colors are saved to workspace settings (which we use for other shared things), and we don't want to force a certain color on everyone for each repo (we'd be bikeshedding for days if we had to decide on that) 😕

Is there any way to have the option to save color settings per directory / repo in user settings rather than in workspace settings?

I have 0 knowledge of VS Code extension development, but I'd be willing to take a crack at implementing this given some time. Not sure how much effort it might be. Looks like maybe [this function](https://github.com/johnpapa/vscode-peacock/blob/master/src/configuration.ts#L67) is a good place to start:

```ts
export async function updateConfiguration<T>(
  setting: AllSettings,
  value?: T | undefined
) {
  let config = vscode.workspace.getConfiguration();
  return await config.update(
    `${extSuffix}.${setting}`,
    value,
    vscode.ConfigurationTarget.Global
  );
}
```

Thanks!

**Comment by granmoe** [comment]
This idea is mentioned in #33

**Comment by granmoe** [comment]
Also, I wonder if most people would want to save colors in user settings as the default rather than in workspace settings.

**Comment by musicfuel** [comment]
See the discussion currently going on in #7 regarding the latest on this.

**Comment by johnpapa** [comment]
You make great points. The current approach requires you to not commit your changes if you dont want it to affect your colleagues.

We are exploring ideas on how to do this in #7 

Please join the discussion ... I'm very open to ideas

**Comment by johnpapa** [comment]
closing in favor of #7 - we do want this feature
