### ISSUE TITLE
Clear all Peacock settings  and colors on uninstall

### ISSUE THREAD

**Issue by johnpapa** [johnpapa/vscode-peacock#98]
From a user ...

> Installed peacock, changed color, didn't really like the result, uninstalled extension, reloaded and my task bar was still colored. Don't know if it's technically possible but it would be thoughtful to perform a "Reset colors" action before uninstalling the extension.

On uninstall this would require clearing the settings and the changes made to the workspace settings. The function exists to do this now with `resetColors`.

Something to consider is if it should ask the user if the colors should be cleared or not.

**Comment by johnpapa** [comment]
some others with a similar idea https://github.com/Microsoft/vscode/issues/45474

**Comment by claviska** [comment]
Just ran into this. It would definitely be thoughtful, as it took a bit to figure out I needed to reinstall the plugin to fix it.

For others googling:

1. Reinstall
2. Run the `Peacock: Reset Colors` command
3. Uninstall

**Comment by johnpapa** [comment]
this would require an uninstall API to tap into.

**Comment by IsaacSomething** [comment]
What about 
```
{
  "scripts": {
    "vscode:uninstall": "node ./out/src/lifecycle"
  }
}
```

**Comment by johnpapa** [comment]
Seeing if anyone wants to take a try at a PR. Otherwise, I'll close this in a few days due to inactivity

**Comment by advaithm** [comment]
> Just ran into this. It would definitely be thoughtful, as it took a bit to figure out I needed to reinstall the plugin to fix it.
> 
> For others googling:
> 
>     1. Reinstall
> 
>     2. Run the `Peacock: Reset Colors` command
> 
>     3. Uninstall

this isn't working for me could some help me fix this

**Comment by johnpapa** [comment]
If the vscode team adds an uninstall API, I will add a work item to to remove peacock on uninstall.

closing til then as there is not work to do at this time.

If you find yourself at this thread and you want to remove Peacock, there are 2 options today:

**option 1**
1. install peacock
1. run the command `Peacock: Reset Colors`
1. uninstall peacock

**option 2**
1. remove all workbench colors from `.vscode/settings.json` that Peacock added
1. remove all `peacock.*` settings from your user settings

**Comment by scullabyte** [comment]
> If the vscode team adds an uninstall API, I will add a work item to to remove peacock on uninstall.
> 
> closing til then as there is not work to do at this time.
> 
> If you find yourself at this thread and you want to remove Peacock, there are 2 options today:
> 
> **option 1**
> 
> 1. install peacock
> 2. run the command `Peacock: Reset Colors`
> 3. uninstall peacock
> 
> **option 2**
> 
> 1. remove all workbench colors from `.vscode/settings.json` that Peacock added
> 2. remove all `peacock.*` settings from your user settings


This doesn't work. I am very annoyed.

**Comment by johnpapa** [comment]
Hi @scullabyte

Please try to be constructive and consider we are all trying to be helpful. 

If you want help please explain what is r working. What happened. What would you like to see. Maybe we can help. 

If you are upset about not being able to remove the settings - I explained this isn’t supported in the code api. You could upvote code GitHub issues for this request.

**Comment by scullabyte** [comment]
I would **highly** recommend not allowing this to overwrite the user's settings and only overwrite the local `.vscode/` settings in the folder it is used. It is **extremely** annoying to intend to test an extension for a few seconds, and end up spending 10-20 minutes digging through the inner workings of VSCode to track down what json I have to change to disable it and bring your VSCode back to normal. 

None of the above worked, but if anyone else is having this problem and wants to go back to normal, `>Preferences: Open User Settings` and comment out all the lines inside:
`  // "workbench.colorCustomizations": {`

the line `remove all workbench colors from .vscode/settings.json that Peacock added` is not helpful because this changed the global vscode `settings.json` and the above leads me to think it changes local files. No other extension I've ever used permanently changes VSCode after you uninstall it. I don't know why this is allowed to be used if it doesn't clean itself up on uninstall.

**Comment by johnpapa** [comment]
@Scullabyte it seems you have reason to think peacock is adding colors to user settings. Let’s discuss your comments 

1. Peacock does not add colors to user settings. 

2. If you are seeing any unexpected behavior it would be helpful to have information on how to reproduce this. 

3. This issue is not the same as what you are stating 

4. You seem to prefer violating the code of conduct by being abusive among other things. I simply won’t engage in this. 

5.  I’m closing this thread and will block you from the repo if you continue 

6. If you can follow the code of conduct and open an issue that show the behavior, steps to reproduce it as best you can, and be constructive that would greatly be appreciated and would result in providing me with what I need to investigate. 

Of course you have the option to not use Peacock and that’s entirely up to you.

**Comment by advaithm** [comment]
@johnpapa i am having the issues described by @scullabyte. please don`t in haste close the issue.
the command `Peacock: Reset Colors` isn't present. remove the lines you have stated did not help ether.

how would i fix this?

**Comment by johnpapa** [comment]
- @advaithm can you open a new issue and use the issue template or help describe the problem ? That would be helpful. Thank you

This issue is for a removal of the colors and settings in uninstall.  I’d reset is not working then please opens new issue. I will lock this thread so we can have a new discussion about about reset if that is an issue.  (Or any other new issue)
